import type { JourneyStepRow, PresenceEventRow, PresenceFact, Readiness } from "@/lib/w04";
import { SATISFYING_FACTS } from "@/lib/w04";

/** COBS OS · operational cockpit — exactly one executable next action. */
export type CockpitTone = "ready" | "attention" | "blocked" | "delayed" | "neutral";
export type CockpitActionKey = "operationNotActive" | "startStep" | "startBoarding" | "resolvePresence" | "resolveChecklist" | "completeBoarding" | "authorizeDeparture" | "recordArrival" | "completeStep" | "completeOperation" | "waiting";
export type CockpitAction = { key: CockpitActionKey; rpc: string | null; anchor: string | null; blocked: boolean; labelKey?: string; ctaKey?: string };
export type CockpitDelay = { state: "unknown" | "early" | "running" | "late"; lateMs: number };
export type StepPresenceSummary = { population: number; present: number; boarded: number; absent: number; pending: number };
const PHYSICAL_PRESENT_FACTS: PresenceFact[] = ["PRESENT_AT_MEETING_POINT", "BOARDED", "DISEMBARKED"];
const ABSENT_FACTS: PresenceFact[] = ["ABSENCE_NOTED", "NO_SHOW_CONFIRMED"];
type RosterLike = { id: string; participation_kind: string; status: string };
function retractedIds(presence: PresenceEventRow[]): Set<string> { const set = new Set<string>(); for (const event of presence) if (event.retracts_presence_event_id) set.add(event.retracts_presence_event_id); return set; }
export function effectivePresenceFact(presence: PresenceEventRow[], stepId: string, participationId: string): PresenceFact | null { const retracted = retractedIds(presence); const rows = presence.filter((event) => event.participation_id === participationId && event.journey_step_id === stepId && event.presence_fact !== "PRESENCE_RETRACTED" && !retracted.has(event.id)).sort((a,b)=>(a.occurred_at < b.occurred_at ? 1 : -1)); return (rows[0]?.presence_fact as PresenceFact | undefined) ?? null; }
export function summarizeStepPresence(input: { step: JourneyStepRow; roster: RosterLike[]; presence: PresenceEventRow[] }): StepPresenceSummary { const {step,roster,presence}=input; const relevant=roster.filter((row)=>step.presence_population === "participants" ? row.participation_kind === "participant" : true); const satisfying=SATISFYING_FACTS[step.presence_requirement]; let present=0,boarded=0,absent=0,pending=0; for(const row of relevant){ const fact=effectivePresenceFact(presence,step.id,row.id); if(fact&&PHYSICAL_PRESENT_FACTS.includes(fact))present++; if(fact==="BOARDED")boarded++; if(fact&&ABSENT_FACTS.includes(fact))absent++; const resolved=row.status === "confirmed" && Boolean(fact&&satisfying.includes(fact)); if(!resolved)pending++; } return {population:relevant.length,present,boarded,absent,pending}; }
function timeOf(raw:string|null|undefined):number|null{if(!raw)return null;const value=new Date(raw).getTime();return Number.isFinite(value)?value:null;}
export function computeStepDelay(step:JourneyStepRow|null,now:number):CockpitDelay{if(!step)return{state:"unknown",lateMs:0};const start=timeOf(step.expected_start??step.planned_start);const end=timeOf(step.expected_end??step.planned_end);if(end!==null&&now>end)return{state:"late",lateMs:now-end};if(start!==null&&now<start)return{state:"early",lateMs:0};if(start!==null||end!==null)return{state:"running",lateMs:0};return{state:"unknown",lateMs:0};}
export type CockpitInput={operationStatus:string|null;current:JourneyStepRow|null;next:JourneyStepRow|null;readiness:Readiness|null;arrived:boolean;boardingStarted:boolean;gatheringStarted?:boolean;boardingCompleted?:boolean;departureAuthorized?:boolean;departed?:boolean;disembarkationCompleted?:boolean;journeyResolved:boolean};
export function deriveNextAction(input:CockpitInput):CockpitAction{const{operationStatus,current,next,readiness,arrived,boardingStarted,boardingCompleted=false,departureAuthorized=false,journeyResolved}=input;if(operationStatus!=="active")return{key:"operationNotActive",rpc:null,anchor:null,blocked:true};if(!current){if(next)return{key:"startStep",rpc:"start_journey_step",anchor:null,blocked:false};if(journeyResolved)return{key:"completeOperation",rpc:null,anchor:null,blocked:false};return{key:"waiting",rpc:null,anchor:null,blocked:false};}
const notReady=readiness?!readiness.ready:false;
/* Meeting STEP_STARTED already means the encounter is open. There is no separate start_gathering RPC in the deployed V3.1 contract. */
if(current.presence_requirement==="boarded"&&!boardingStarted)return{key:"startBoarding",rpc:"start_boarding",anchor:null,blocked:false};
if(current.step_kind==="disembarkation"&&!arrived)return{key:"recordArrival",rpc:"record_arrival",anchor:null,blocked:false};
if(notReady&&(readiness?.missing_required_items.length??0)>0)return{key:"resolveChecklist",rpc:null,anchor:"cockpit-checklist",blocked:true};
if(notReady&&(readiness?.missing_participations.length??0)>0)return{key:"resolvePresence",rpc:null,anchor:"cockpit-people",blocked:true};
if(current.presence_requirement==="boarded"){if(!boardingCompleted)return{key:"completeBoarding",rpc:"complete_boarding",anchor:null,blocked:notReady,labelKey:"w04.action.completeBoarding",ctaKey:"w04.action.completeBoarding"};if(!departureAuthorized)return{key:"authorizeDeparture",rpc:"authorize_departure",anchor:null,blocked:false,labelKey:"w04.action.authorizeDeparture",ctaKey:"w04.action.authorizeDeparture"};/* V3.1 currently has no record_departed RPC; close the ready boarding step through the canonical step completion command. */}
const needsArrival=current.step_kind==="movement"||current.step_kind==="arrival"||current.step_kind==="return"||current.step_kind==="disembarkation";if(needsArrival&&!arrived)return{key:"recordArrival",rpc:"record_arrival",anchor:null,blocked:false};
return{key:"completeStep",rpc:"complete_journey_step",anchor:null,blocked:notReady,labelKey:"w04.action.completeStep",ctaKey:"w04.action.completeStep"};}
export function deriveTone(input:{action:CockpitAction;delay:CockpitDelay;summary:StepPresenceSummary|null;operationStatus:string|null}):CockpitTone{const{action,delay,summary,operationStatus}=input;if(operationStatus!=="active")return"neutral";if(action.blocked)return"blocked";if(delay.state==="late")return"delayed";if(summary&&(summary.pending>0||summary.absent>0))return"attention";return"ready";}
