import { FormEvent, useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Car, CheckCircle2, Compass, Heart, Loader2, MapPin, ShieldCheck, Sparkles, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/chapada-experience")({
  head: () => ({ meta: [
    { title: "Chapada Experience — Privativo Casal | BSBTUR" },
    { name: "description", content: "Seis dias na Chapada dos Veadeiros em uma experiência privativa para duas pessoas, com 4x4, acompanhamento e curadoria BSBTUR." },
    { property: "og:title", content: "Chapada Experience — Privativo Casal | BSBTUR" },
    { property: "og:description", content: "Vocês escolhem a Chapada. A BSBTUR cuida do caminho — e guarda algumas surpresas." },
  ]}), component: ChapadaExperience,
});

const gold = "#D6B56D";
const days = [
  ["01", "15 JUN", "Brasília → Alto Paraíso", "Recepção em Brasília, saída em 4x4 privativo, chegada ao Woodstock Guesthouse e experiência de boas-vindas."],
  ["02", "16 JUN", "Parque Nacional", "Um dos grandes dias da viagem. O circuito será escolhido conforme clima, perfil do casal e regras vigentes, priorizando as melhores condições da data."],
  ["03", "17 JUN", "Vale da Lua + São Jorge", "Paisagens marcantes, contemplação, tempo para viver São Jorge, gastronomia e uma experiência local preparada para o casal."],
  ["04", "18 JUN", "Almécegas + São Bento", "Cachoeiras, trilhas, banho, fotografia e tempo para aproveitar a Chapada sem transformar o dia em uma corrida de atrações."],
  ["05", "19 JUN", "Cavalcante + Kalunga + Santa Bárbara", "O grande dia da viagem: 4x4, território Kalunga e Santa Bárbara, sujeita à confirmação operacional e às regras locais vigentes."],
  ["06", "20 JUN", "Alto Paraíso → Brasília", "Café da manhã tranquilo, despedida da Chapada e retorno privativo a Brasília com acompanhamento até o desembarque final."],
] as const;
const inclusions = [
  [Heart, "Hospedagem selecionada", "5 noites no Woodstock Guesthouse, com acomodação do casal e café da manhã conforme serviço da hospedagem."],
  [Car, "4x4 privativo", "Categoria de referência Localiza Grupo P — S10, Frontier ou similar — para a operação."],
  [Users, "Acompanhamento", "Guia de Excursão Nacional acompanhando a experiência do embarque em Brasília ao desembarque final."],
  [Compass, "Curadoria BSBTUR", "Roteiro, planejamento e suporte para que o casal aproveite o destino com mais liberdade e menos preocupação."],
  [MapPin, "Experiências e atrativos", "Acessos previstos na composição final da viagem, respeitando as regras e condições vigentes de cada local."],
  [ShieldCheck, "Seguro viagem", "Proteção para os dois viajantes durante a operação, conforme condições da apólice contratada."],
] as const;

function Signature() { return <div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full border text-sm font-bold" style={{ borderColor: gold, color: gold }}>B</span><span><span className="block font-semibold tracking-[.18em] text-white">BSBTUR</span><span className="block text-[9px] uppercase tracking-[.28em] text-white/45">Turismo & Experiências</span></span></div>; }

function ChapadaExperience() {
  const [fullName,setFullName]=useState(""); const [email,setEmail]=useState(""); const [phone,setPhone]=useState("");
  const [consent,setConsent]=useState(false); const [loading,setLoading]=useState(false); const [submitted,setSubmitted]=useState(false); const [error,setError]=useState<string|null>(null);
  const idempotencyKey=useMemo(()=>crypto.randomUUID(),[]);
  async function submitLead(event: FormEvent) {
    event.preventDefault(); if (loading || !consent) return; setLoading(true); setError(null);
    try { const {data,error:captureError}=await supabase.functions.invoke("chapada-public-lead-capture",{body:{full_name:fullName,email,phone,consent_contact:consent,idempotency_key:idempotencyKey}}); if(captureError) throw captureError; if(!data?.id) throw new Error("lead_capture_response_invalid"); setSubmitted(true); }
    catch { setError("Não foi possível registrar seu interesse agora. Revise os dados e tente novamente em instantes."); }
    finally { setLoading(false); }
  }
  return <div className="min-h-screen bg-[#070707] text-white selection:bg-[#D6B56D] selection:text-black">
    <header className="sticky top-0 z-30 border-b border-white/10 bg-black/75 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><Signature/><a href="#proposta"><Button className="rounded-full bg-[#D6B56D] px-5 font-semibold text-black hover:bg-[#ead293]">Quero viver essa experiência</Button></a></div></header>
    <main>
      <section className="relative overflow-hidden border-b border-white/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(214,181,109,.18),transparent_25%),radial-gradient(circle_at_20%_80%,rgba(80,120,72,.14),transparent_28%)]"/><div className="relative mx-auto grid min-h-[78vh] max-w-6xl items-center gap-12 px-5 py-20 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-xs font-bold uppercase tracking-[.25em]" style={{color:gold}}>BSBTUR Experience • Edição Privativa</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold leading-[.94] tracking-[-.04em] sm:text-7xl">Chapada Experience</h1><p className="mt-5 text-xl font-medium" style={{color:gold}}>Privativo Casal • 15 a 20 de junho de 2027</p><p className="mt-6 max-w-2xl text-lg leading-8 text-white/65">Seis dias para viver a Chapada dos Veadeiros com privacidade, tempo, cuidado e pequenas surpresas preparadas pela BSBTUR. Não é sobre correr para conhecer tudo. É sobre viver bem cada lugar.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#roteiro"><Button className="rounded-full bg-[#D6B56D] px-6 text-black hover:bg-[#ead293]">Conhecer a experiência</Button></a><a href="#incluso"><Button variant="outline" className="rounded-full border-white/20 bg-transparent px-6 text-white hover:bg-white/10">Ver o que está incluído</Button></a></div><div className="mt-8 flex flex-wrap gap-2 text-xs text-white/60">{["2 viajantes","6 dias / 5 noites","4x4 privativo","Guia de Excursão Nacional","Surpresas BSBTUR"].map(x=><span key={x} className="rounded-full border border-white/10 bg-white/[.03] px-3 py-2">{x}</span>)}</div></div><div className="relative min-h-[440px] overflow-hidden rounded-[2rem] border border-[#D6B56D]/25 bg-[linear-gradient(145deg,#403821,#697048_28%,#213b2d_52%,#0b1713_75%,#080808)] shadow-2xl"><div className="absolute right-[14%] top-[13%] size-24 rounded-full bg-[#D6B56D] shadow-[0_0_80px_rgba(214,181,109,.45)]"/><div className="absolute inset-x-6 bottom-6 rounded-3xl border border-white/10 bg-black/55 p-6 backdrop-blur-xl"><Sparkles className="mb-3" style={{color:gold}}/><p className="text-2xl font-semibold">Uma Chapada só para vocês.</p><p className="mt-2 text-sm leading-6 text-white/60">Vocês escolhem o destino. A BSBTUR cuida do caminho — e algumas coisas vocês só descobrem lá.</p></div></div></div></section>
      <section className="mx-auto max-w-6xl px-5 py-20"><div className="grid gap-8 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.24em]" style={{color:gold}}>O conceito</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">O luxo aqui é outro.</h2></div><p className="text-lg leading-8 text-white/60">Tempo para contemplar. Privacidade para viajar no próprio ritmo. Mobilidade 4x4. Acompanhamento profissional. Curadoria. Segurança. E a sensação de que alguém pensou nos detalhes antes de vocês chegarem.</p></div></section>
      <section id="roteiro" className="border-y border-white/10 bg-white/[.025]"><div className="mx-auto max-w-6xl px-5 py-20"><p className="text-xs font-bold uppercase tracking-[.24em]" style={{color:gold}}>6 dias de experiência</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">O roteiro dia a dia.</h2><div className="mt-10 space-y-3">{days.map(([n,date,title,text],i)=><article key={n} className="grid gap-4 rounded-3xl border border-white/10 bg-black/35 p-6 md:grid-cols-[90px_1fr_auto]"><div className="text-xs font-bold tracking-[.18em]" style={{color:gold}}>DIA {n}<br/>{date}</div><div><h3 className="text-xl font-semibold">{title}</h3><p className="mt-2 max-w-3xl leading-7 text-white/55">{text}</p></div><span className="h-fit w-fit rounded-full bg-[#D6B56D] px-3 py-2 text-[10px] font-bold uppercase tracking-wider text-black">{i===4?"A grande surpresa":i===5?"Surpresa final":`Surpresa #${i+1}`}</span></article>)}</div><p className="mt-6 text-sm leading-6 text-white/40">A sequência poderá ser ajustada por clima, segurança, disponibilidade, capacidade de visitação e regras dos atrativos, preservando a essência da experiência.</p></div></section>
      <section id="incluso" className="mx-auto max-w-6xl px-5 py-20"><p className="text-xs font-bold uppercase tracking-[.24em]" style={{color:gold}}>Antes de falar em investimento</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-tight sm:text-5xl">Veja tudo o que compõe a experiência.</h2><div className="mt-10 grid gap-4 md:grid-cols-2">{inclusions.map(([Icon,title,text])=><article key={title} className="rounded-3xl border border-white/10 bg-white/[.025] p-6"><Icon className="size-6" style={{color:gold}}/><h3 className="mt-4 text-xl font-semibold">{title}</h3><p className="mt-2 leading-7 text-white/55">{text}</p></article>)}</div></section>
      <section className="border-y border-white/10 bg-white/[.025]"><div className="mx-auto max-w-6xl px-5 py-20"><div className="grid gap-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.24em]" style={{color:gold}}>Assinatura BSBTUR</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Várias surpresas. Nenhuma viagem igual.</h2></div><div><p className="text-lg leading-8 text-white/60">O casal conhece o roteiro principal, mas não todos os pequenos momentos que preparamos. Kit de boas-vindas, experiência local, mimo, parada contemplativa, presente artesanal ou um encerramento especial podem fazer parte da jornada.</p><p className="mt-5 font-semibold" style={{color:gold}}>A promessa não é ostentação. É cuidado, memória e descoberta.</p></div></div></div></section>
      <section id="proposta" className="mx-auto max-w-6xl px-5 py-24"><div className="rounded-[2rem] border border-[#D6B56D]/30 bg-[radial-gradient(circle_at_top,rgba(214,181,109,.15),transparent_35%)] p-8 sm:p-14"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[.24em]" style={{color:gold}}>Investimento • somente no fechamento</p><h2 className="mx-auto mt-4 max-w-3xl text-4xl font-semibold tracking-tight sm:text-5xl">Agora que vocês conhecem a experiência, solicitem a proposta do casal.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-white/60">A condição comercial será apresentada após confirmação da disponibilidade e dos serviços desta saída.</p></div>{submitted?<div className="mx-auto mt-10 max-w-xl rounded-3xl border border-[#D6B56D]/30 bg-black/35 p-8 text-center"><CheckCircle2 className="mx-auto size-9" style={{color:gold}}/><h3 className="mt-4 text-2xl font-semibold">Interesse registrado.</h3><p className="mt-2 text-white/55">A equipe BSBTUR poderá entrar em contato pelos dados informados para apresentar a proposta desta experiência.</p></div>:<form onSubmit={submitLead} className="mx-auto mt-10 max-w-xl space-y-4"><Input required minLength={2} maxLength={120} value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Nome completo" className="border-white/15 bg-black/35 text-white placeholder:text-white/35"/><Input required type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail" className="border-white/15 bg-black/35 text-white placeholder:text-white/35"/><Input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="WhatsApp com DDD" className="border-white/15 bg-black/35 text-white placeholder:text-white/35"/><label className="flex items-start gap-3 text-sm leading-6 text-white/55"><input required type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1"/><span>Autorizo a BSBTUR a entrar em contato comigo sobre a Chapada Experience e esta solicitação de proposta.</span></label>{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}<Button type="submit" disabled={loading||!consent} className="w-full rounded-full bg-[#D6B56D] py-6 text-base font-semibold text-black hover:bg-[#ead293] disabled:opacity-50">{loading?<><Loader2 className="mr-2 size-4 animate-spin"/>Registrando...</>:"Solicitar proposta do casal"}</Button><p className="text-center text-xs text-white/35">Solicitar a proposta não gera pedido, reserva, Pix ou cobrança.</p></form>}</div></section>
    </main><footer className="border-t border-white/10"><div className="mx-auto flex max-w-6xl flex-col gap-5 px-5 py-8 text-sm text-white/40 sm:flex-row sm:items-center sm:justify-between"><Signature/><span>Chapada Experience • Privativo Casal • 15–20/06/2027</span></div></footer>
  </div>;
}
