import { FormEvent, useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, Crown, GraduationCap, HeartHandshake, Hotel, Loader2, MapPin, Plane, ShieldCheck, Sparkles, Users, UtensilsCrossed } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/ciosp-2027")({
  head: () => ({ meta: [
    { title: "CIOSP 2027 — Experiência Premium BSBTUR" },
    { name: "description", content: "Experiência acadêmica premium BSBTUR para o CIOSP 2027 em São Paulo, de 25 a 31 de janeiro de 2027." },
  ]}),
  component: CiospPrelaunch,
});

const gold = "#D6B56D";
const inclusions = [
  [Plane, "Passagem aérea", "Brasília → São Paulo → Brasília, conforme contratação final."],
  [Hotel, "Hospedagem", "6 diárias em acomodação dupla, com café da manhã."],
  [MapPin, "Mobilidade em São Paulo", "Transfers e deslocamentos previstos na programação da caravana."],
  [GraduationCap, "CIOSP 2027", "Participação acadêmica conforme a modalidade contemplada no pacote final."],
  [ShieldCheck, "Seguro viagem", "Proteção para os viajantes durante o período da operação."],
  [HeartHandshake, "Equipe BSBTUR", "Acompanhamento e suporte operacional durante toda a experiência."],
] as const;
const images = [
  ["https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1600&q=88", "Congresso & formação"],
  ["https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=88", "Viagem organizada"],
  ["https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=88", "Hospedagem confortável"],
] as const;

function BsbTurSignature() {
  return <div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full border text-sm font-bold" style={{borderColor:gold,color:gold}}>B</span><span><span className="block text-base font-semibold tracking-[0.18em] text-white">BSBTUR</span><span className="block text-[9px] uppercase tracking-[0.28em] text-white/45">Turismo & Experiências</span></span></div>;
}

function CiospPrelaunch() {
  const [fullName,setFullName]=useState(""); const [email,setEmail]=useState(""); const [phone,setPhone]=useState("");
  const [consentContact,setConsentContact]=useState(false); const [submitted,setSubmitted]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null);
  const idempotencyKey=useMemo(()=>crypto.randomUUID(),[]);
  async function submit(event:FormEvent){event.preventDefault();if(loading||!consentContact)return;setLoading(true);setError(null);try{const {data,error:captureError}=await supabase.functions.invoke("ciosp-public-lead-capture",{body:{full_name:fullName,email,phone,consent_contact:consentContact,idempotency_key:idempotencyKey,source:"ciosp_2027_prelaunch",campaign:"ciosp-2027-lista-prioritaria"}});if(captureError)throw captureError;if(!data?.id)throw new Error("lead_capture_response_invalid");setSubmitted(true)}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível registrar seu interesse agora.")}finally{setLoading(false)}}
  return <div className="min-h-screen bg-[#070707] text-[#F5F1E8]">
    <header className="sticky top-0 z-40 border-b border-white/10 bg-[#070707]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><BsbTurSignature/><a href="#lista-prioritaria" className="hidden rounded-full border px-5 py-2.5 text-sm font-semibold transition hover:bg-white/5 sm:inline-flex" style={{borderColor:`${gold}66`,color:gold}}>Lista prioritária <ArrowRight className="ml-2 size-4"/></a></div></header>
    <main>
      <section className="relative isolate overflow-hidden border-b border-white/10">
        <img src={images[0][0]} alt="Imagem ilustrativa de congresso" className="absolute inset-0 -z-30 h-full w-full object-cover opacity-30"/>
        <div className="absolute inset-0 -z-20 bg-gradient-to-r from-black via-black/90 to-black/55"/><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_75%_45%,rgba(214,181,109,0.13),transparent_32%)]"/>
        <div className="mx-auto grid min-h-[760px] max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-[1.12fr_.88fr] lg:px-8 lg:py-28">
          <div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-[#D6B56D]/35 bg-[#D6B56D]/10 px-4 py-2 text-xs font-semibold uppercase tracking-[.18em] text-[#E4CA91]"><Sparkles className="size-4"/> CIOSP 2027 · Edição Premium</div>
          <p className="mt-8 text-sm uppercase tracking-[.24em] text-white/50">25–31 janeiro · Brasília → São Paulo</p><h1 className="mt-4 text-5xl font-semibold leading-[.98] tracking-tight sm:text-6xl lg:text-7xl">Uma experiência à altura do seu próximo grande passo.</h1>
          <p className="mt-7 max-w-2xl text-lg leading-relaxed text-white/65 sm:text-xl">CIOSP 2027 com a jornada organizada pela BSBTUR — viagem, hospedagem, mobilidade e acompanhamento para você viver São Paulo com foco total na sua formação.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#lista-prioritaria" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full px-7 py-3 font-semibold text-black transition hover:brightness-110" style={{background:`linear-gradient(135deg,#F0D9A3,${gold},#B78B38)`}}>Quero prioridade <ArrowRight className="size-4"/></a><a href="#experiencia" className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/20 bg-black/20 px-7 py-3 font-semibold text-white/85 backdrop-blur">Descobrir a experiência</a></div>
          <div className="mt-10 flex flex-wrap gap-6 text-sm text-white/55"><span><Users className="mr-2 inline size-4" style={{color:gold}}/>30 vagas planejadas</span><span><Hotel className="mr-2 inline size-4" style={{color:gold}}/>6 diárias</span><span><ShieldCheck className="mr-2 inline size-4" style={{color:gold}}/>Suporte BSBTUR</span></div></div>
          <div className="lg:justify-self-end"><div className="w-full max-w-md rounded-[2rem] border bg-black/60 p-7 shadow-2xl backdrop-blur-xl" style={{borderColor:`${gold}55`,boxShadow:`0 30px 90px rgba(0,0,0,.55),0 0 55px rgba(214,181,109,.08)`}}><div className="flex items-center justify-between"><span className="text-sm text-white/45">Pré-lançamento 2027</span><Crown className="size-5" style={{color:gold}}/></div><p className="mt-9 text-xs uppercase tracking-[.18em] text-white/45">Investimento planejado</p><p className="mt-2 text-5xl font-semibold tracking-tight text-[#F5E7C5]">R$ 9.990</p><p className="mt-3 text-sm leading-relaxed text-white/55">Entrada planejada de <strong className="text-white">R$ 2.490</strong> + saldo conforme as condições da contratação.</p><div className="my-7 h-px bg-[#D6B56D]/20"/><div className="space-y-3 text-sm text-white/70">{["Experiência acadêmica integrada","Viagem com acompanhamento","Comunicação centralizada","Sem cobrança nesta etapa"].map(x=><div key={x} className="flex items-center gap-3"><CheckCircle2 className="size-4" style={{color:gold}}/>{x}</div>)}</div></div></div>
        </div>
      </section>
      <section id="experiencia" className="bg-[#0B0B0B]"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid items-end gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.22em]" style={{color:gold}}>Mais que uma viagem</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Uma semana desenhada para ser inesquecível.</h2></div><p className="max-w-2xl text-lg leading-relaxed text-white/50 lg:justify-self-end">Menos preocupação com logística. Mais tempo para conhecimento, conexões e tudo o que o maior encontro da Odontologia pode representar para a sua trajetória.</p></div>
      <div className="mt-12 grid gap-4 lg:grid-cols-12 lg:grid-rows-2">{images.map(([src,label],i)=><figure key={src} className={`group relative overflow-hidden rounded-[2rem] border border-white/10 bg-black ${i===0?"min-h-[480px] lg:col-span-7 lg:row-span-2":"min-h-[230px] lg:col-span-5"}`}><img src={src} alt={`Imagem ilustrativa: ${label}`} className="absolute inset-0 h-full w-full object-cover opacity-75 grayscale-[15%] transition duration-700 group-hover:scale-[1.03]" loading="lazy"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/10 to-transparent"/><figcaption className="absolute bottom-0 p-7"><p className="text-xs uppercase tracking-[.2em]" style={{color:gold}}>{label}</p>{i===0&&<p className="mt-2 max-w-md text-2xl font-semibold">Conhecimento, inovação e conexões no centro da experiência.</p>}</figcaption></figure>)}</div><p className="mt-4 text-xs text-white/35">Imagens ilustrativas. Fornecedores, ambientes e serviços definitivos serão informados nas condições de contratação.</p></div></section>
      <section className="border-y border-[#D6B56D]/15 bg-[#050505]"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24"><p className="text-xs font-bold uppercase tracking-[.22em]" style={{color:gold}}>Tudo em uma única jornada</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold sm:text-5xl">Você cuida do CIOSP. A BSBTUR cuida da experiência.</h2><div className="mt-12 grid gap-px overflow-hidden rounded-[2rem] border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{inclusions.map(([Icon,title,description])=><article key={title} className="bg-[#090909] p-8"><span className="grid size-11 place-items-center rounded-full border border-[#D6B56D]/25 bg-[#D6B56D]/5" style={{color:gold}}><Icon className="size-5"/></span><h3 className="mt-6 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-white/45">{description}</p></article>)}</div><div className="mt-6 flex gap-3 rounded-2xl border border-[#D6B56D]/15 bg-[#D6B56D]/5 p-5 text-sm text-white/55"><UtensilsCrossed className="size-5 shrink-0" style={{color:gold}}/>Alimentação programada e kit BSBTUR fazem parte do planejamento comercial e serão detalhados nas condições finais.</div></div></section>
      <section id="lista-prioritaria" className="bg-[#0B0B0B]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[.85fr_1.15fr] lg:px-8 lg:py-28"><div><p className="text-xs font-bold uppercase tracking-[.22em]" style={{color:gold}}>Lista prioritária</p><h2 className="mt-4 text-4xl font-semibold sm:text-5xl">Seu lugar começa com uma decisão.</h2><p className="mt-5 max-w-xl text-lg leading-relaxed text-white/50">Cadastre seu interesse para receber prioridade quando as condições comerciais e reservas forem abertas. Nesta etapa não há cobrança nem garantia de vaga.</p><div className="mt-9 rounded-2xl border border-[#D6B56D]/20 bg-[#D6B56D]/5 p-5 text-sm text-white/55"><strong className="text-[#E4CA91]">CIOSP 2027 · BSBTUR</strong><br/>25–31 janeiro · Brasília → São Paulo · 30 vagas planejadas</div></div>
      <div className="rounded-[2rem] border border-[#D6B56D]/25 bg-[#111]/90 p-6 shadow-2xl sm:p-8">{!submitted?<form onSubmit={submit} className="space-y-4"><div><p className="text-xs uppercase tracking-[.2em]" style={{color:gold}}>Manifestação de interesse</p><h3 className="mt-2 text-2xl font-semibold">Quero receber prioridade</h3></div><label className="block space-y-1.5 text-sm">Nome completo<Input required minLength={2} maxLength={120} value={fullName} onChange={e=>setFullName(e.target.value)} autoComplete="name" className="border-white/15 bg-black/40 text-white"/></label><label className="block space-y-1.5 text-sm">WhatsApp<Input required value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel" placeholder="(61) 99999-9999" className="border-white/15 bg-black/40 text-white"/></label><label className="block space-y-1.5 text-sm">E-mail<Input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" className="border-white/15 bg-black/40 text-white"/></label><label className="flex items-start gap-3 rounded-xl border border-white/10 bg-black/30 p-4 text-sm text-white/60"><input required type="checkbox" checked={consentContact} onChange={e=>setConsentContact(e.target.checked)} className="mt-1 size-4"/><span>Autorizo a BSBTUR a entrar em contato comigo sobre a Caravana CIOSP 2027. Posso solicitar a interrupção do contato a qualquer momento.</span></label>{error&&<div className="rounded-lg border border-red-900/50 bg-red-950/20 p-3 text-sm text-red-300">{error}</div>}<Button type="submit" size="lg" className="w-full bg-[#D6B56D] text-black hover:bg-[#E4CA91]" disabled={loading||!consentContact}>{loading?<><Loader2 className="mr-2 size-4 animate-spin"/>Registrando...</>:"Entrar na lista prioritária"}</Button><p className="text-center text-xs text-white/35">Sem pagamento e sem reserva nesta etapa.</p></form>:<div className="py-10 text-center"><CheckCircle2 className="mx-auto size-12" style={{color:gold}}/><h3 className="mt-5 text-2xl font-semibold">Você entrou na lista prioritária</h3><p className="mt-2 text-sm text-white/50">Seu interesse foi registrado no COBS. A BSBTUR poderá entrar em contato quando houver novidades.</p></div>}</div></div></section>
    </main><footer className="border-t border-white/10 bg-black"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-xs text-white/35 sm:flex-row sm:items-center sm:justify-between lg:px-8"><BsbTurSignature/><span>CIOSP 2027 · Pré-lançamento · Imagens ilustrativas</span></div></footer>
  </div>;
}
