import { createFileRoute } from "@tanstack/react-router";
import { createClient } from "@supabase/supabase-js";

import type { Database } from "@/integrations/supabase/types";
import { createMercadoPagoProvider } from "@/lib/payments-mp.server";
import { paymentAttemptRequestSchema, sanitizePaymentAttemptResponse } from "@/lib/payments-api";

function userSupabaseClient(token: string) {
  const url = process.env["SUPABASE_URL"] ?? import.meta.env["VITE_SUPABASE_URL"];
  const key =
    process.env["SUPABASE_PUBLISHABLE_KEY"] ?? import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"];
  if (!url || !key) return null;

  return createClient<Database>(url, key, {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

// routeTree.gen.ts is regenerated by the TanStack Vite plugin during build.
// @ts-expect-error -- this new literal route is discovered after the pre-build typecheck.
export const Route = createFileRoute("/api/payments/attempts")({
  server: {
    handlers: {
      POST: async ({ request }) => {
        const authHeader = request.headers.get("authorization") ?? "";
        if (!authHeader.startsWith("Bearer ")) {
          return Response.json({ error: "unauthorized" }, { status: 401 });
        }
        const token = authHeader.slice("Bearer ".length).trim();
        if (!token) {
          return Response.json({ error: "unauthorized" }, { status: 401 });
        }

        const supabase = userSupabaseClient(token);
        if (!supabase) {
          return Response.json({ error: "auth_not_configured" }, { status: 503 });
        }

        const { data: authData, error: authError } = await supabase.auth.getUser(token);
        if (authError || !authData.user) {
          return Response.json({ error: "unauthorized" }, { status: 401 });
        }

        const parsed = paymentAttemptRequestSchema.safeParse(
          await request.json().catch(() => null),
        );
        if (!parsed.success) {
          return Response.json({ error: "invalid_payload" }, { status: 400 });
        }

        const { data, error } = await supabase.rpc("create_payment_attempt", {
          _payment_order_id: parsed.data.payment_order_id,
          _payment_method: parsed.data.payment_method,
          _idempotency_key: parsed.data.idempotency_key,
        });
        if (error) {
          const denied = /permission|authentication|required|not found/i.test(error.message);
          return Response.json(
            { error: denied ? "payment_not_allowed" : "attempt_failed" },
            { status: denied ? 403 : 400 },
          );
        }

        const safeAttempt = sanitizePaymentAttemptResponse(data);
        if (!safeAttempt) {
          return Response.json({ error: "invalid_attempt_response" }, { status: 500 });
        }

        // MP-01 exercises the provider boundary without creating a real charge.
        const provider = createMercadoPagoProvider();
        const amount = typeof safeAttempt["amount"] === "number" ? safeAttempt["amount"] : 0;
        const currency =
          typeof safeAttempt["currency"] === "string" ? safeAttempt["currency"] : "BRL";
        const externalReference =
          typeof safeAttempt["external_reference"] === "string"
            ? safeAttempt["external_reference"]
            : "";
        await provider.createPayment({
          externalReference,
          amount,
          currency,
          paymentMethod: parsed.data.payment_method,
          description: "COBS payment",
        });

        return Response.json({ ...safeAttempt, provider_payment_created: false }, { status: 201 });
      },
    },
  },
});
