import { createFileRoute } from "@tanstack/react-router";
import { createClient } from "@supabase/supabase-js";

import type { Database } from "@/integrations/supabase/types";
import { createMercadoPagoProvider, toCanonicalProviderEvent } from "@/lib/payments-mp.server";
import { paymentAttemptRequestSchema, sanitizePaymentAttemptResponse } from "@/lib/payments-api";

function userSupabaseClient(token: string) {
  const url = process.env["SUPABASE_URL"] ?? import.meta.env["VITE_SUPABASE_URL"];
  const key =
    process.env["SUPABASE_PUBLISHABLE_KEY"] ?? import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"];
  if (!url || !key) return null;

  return createClient<Database>(url, key, {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

// routeTree.gen.ts is regenerated by the TanStack Vite plugin during build.

export const Route = createFileRoute("/api/payments/attempts")({
  server: {
    handlers: {
      POST: async ({ request }) => {
        const authHeader = request.headers.get("authorization") ?? "";
        if (!authHeader.startsWith("Bearer ")) {
          return Response.json({ error: "unauthorized" }, { status: 401 });
        }
        const token = authHeader.slice("Bearer ".length).trim();
        if (!token) {
          return Response.json({ error: "unauthorized" }, { status: 401 });
        }

        const supabase = userSupabaseClient(token);
        if (!supabase) {
          return Response.json({ error: "auth_not_configured" }, { status: 503 });
        }

        const { data: authData, error: authError } = await supabase.auth.getUser(token);
        if (authError || !authData.user) {
          return Response.json({ error: "unauthorized" }, { status: 401 });
        }

        const parsed = paymentAttemptRequestSchema.safeParse(
          await request.json().catch(() => null),
        );
        if (!parsed.success) {
          return Response.json({ error: "invalid_payload" }, { status: 400 });
        }
        if (parsed.data.payment_method !== "pix") {
          return Response.json({ error: "payment_method_not_enabled" }, { status: 422 });
        }
        if (!authData.user.email) {
          return Response.json({ error: "payer_email_required" }, { status: 422 });
        }

        const { data, error } = await supabase.rpc("create_payment_attempt", {
          _payment_order_id: parsed.data.payment_order_id,
          _payment_method: parsed.data.payment_method,
          _idempotency_key: parsed.data.idempotency_key,
        });
        if (error) {
          const denied = /permission|authentication|required|not found/i.test(error.message);
          return Response.json(
            { error: denied ? "payment_not_allowed" : "attempt_failed" },
            { status: denied ? 403 : 400 },
          );
        }

        const safeAttempt = sanitizePaymentAttemptResponse(data);
        if (!safeAttempt) {
          return Response.json({ error: "invalid_attempt_response" }, { status: 500 });
        }

        const amount = typeof safeAttempt["amount"] === "number" ? safeAttempt["amount"] : 0;
        const currency =
          typeof safeAttempt["currency"] === "string" ? safeAttempt["currency"] : "BRL";
        const externalReference =
          typeof safeAttempt["external_reference"] === "string"
            ? safeAttempt["external_reference"]
            : "";
        if (!amount || !externalReference || currency !== "BRL") {
          return Response.json({ error: "invalid_attempt_contract" }, { status: 500 });
        }

        const accessToken = process.env["MP_ACCESS_TOKEN"];
        if (!accessToken) {
          return Response.json({ error: "provider_not_configured" }, { status: 503 });
        }

        const provider = createMercadoPagoProvider({ accessToken });
        const providerPayment = await provider.createPayment({
          externalReference,
          amount,
          currency,
          paymentMethod: "pix",
          description: "COBS payment",
          payerEmail: authData.user.email,
          idempotencyKey: parsed.data.idempotency_key,
        });
        if (!providerPayment) {
          return Response.json({ error: "provider_creation_failed" }, { status: 502 });
        }
        if (
          providerPayment.external_reference !== externalReference ||
          providerPayment.amount !== amount ||
          providerPayment.currency !== currency
        ) {
          return Response.json({ error: "provider_contract_mismatch" }, { status: 502 });
        }

        const canonical = toCanonicalProviderEvent(providerPayment);
        if (!canonical) {
          return Response.json({ error: "provider_status_unmapped" }, { status: 502 });
        }

        const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
        const { error: recordError } = await supabaseAdmin.rpc("record_provider_payment_event", {
          _provider: "mercadopago",
          _event_type: canonical.eventType,
          _external_reference: externalReference,
          _provider_payment_id: canonical.providerPaymentId,
          _provider_event_id: `create:${canonical.providerPaymentId}`,
          _provider_status: canonical.providerStatus,
          _amount: canonical.amount,
          _payload: { source: "pix_order_create", reconciled: true },
          ...(canonical.providerStatusDetail
            ? { _provider_status_detail: canonical.providerStatusDetail }
            : {}),
          ...(canonical.occurredAt ? { _occurred_at: canonical.occurredAt } : {}),
        });
        if (recordError) {
          console.error("[MP-02B] provider creation could not be recorded", recordError.message);
          return Response.json({ error: "provider_record_failed" }, { status: 500 });
        }

        return Response.json(
          {
            ...safeAttempt,
            provider_payment_created: true,
            provider_order_id: canonical.providerPaymentId,
            provider_status: canonical.providerStatus,
            provider_status_detail: canonical.providerStatusDetail,
            pix_qr_code: providerPayment.pix_qr_code ?? null,
            pix_qr_code_base64: providerPayment.pix_qr_code_base64 ?? null,
            pix_ticket_url: providerPayment.pix_ticket_url ?? null,
          },
          { status: 201 },
        );
      },
    },
  },
});
