import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SECRET_KEYS = JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS") ?? "{}");
const secretKey = SUPABASE_SECRET_KEYS.default;
const MP_ENVIRONMENT = Deno.env.get("MERCADO_PAGO_ENVIRONMENT") ?? "test";
const MP_TEST_ACCESS_TOKEN = Deno.env.get("MERCADO_PAGO_TEST_ACCESS_TOKEN");
const CANONICAL_CIOSP_OPERATION_CODE = "CIOSP-SP-2027-COMMERCIAL";
const cors = { "access-control-allow-origin": "*", "access-control-allow-headers": "content-type, x-client-info, apikey, authorization", "access-control-allow-methods": "POST, OPTIONS" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "content-type": "application/json; charset=utf-8" } });
const hex = (bytes: ArrayBuffer) => Array.from(new Uint8Array(bytes)).map((b) => b.toString(16).padStart(2, "0")).join("");
async function sha256(value: string) { return hex(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value))); }
function mapAttemptStatus(status?: string, detail?: string) { if (status === "approved") return "approved"; if (status === "processed" && detail === "accredited") return "approved"; if (status === "processed" || status === "processing") return "processing"; if (status === "action_required") return "pending"; if (status === "cancelled") return "cancelled"; if (status === "expired") return "expired"; if (status === "refunded") return "refunded"; if (status === "rejected") return "rejected"; return "pending"; }
Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });
  if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405);
  if (!secretKey) return json({ error: "server_not_configured" }, 500);
  if (MP_ENVIRONMENT !== "test") return json({ error: "public_pix_test_only" }, 503);
  if (!MP_TEST_ACCESS_TOKEN) return json({ error: "mercado_pago_test_not_configured" }, 500);
  let input: { order_id?: string; checkout_token?: string; payer_email?: string }; try { input = await req.json(); } catch { return json({ error: "invalid_json" }, 400); }
  const orderId = (input.order_id ?? "").trim(); const token = (input.checkout_token ?? "").trim(); const payerEmail = (input.payer_email ?? "").trim().toLowerCase();
  if (!/^[0-9a-f-]{36}$/i.test(orderId)) return json({ error: "invalid_order_id" }, 400); if (!/^[0-9a-f]{64}$/i.test(token)) return json({ error: "invalid_checkout_token" }, 400); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(payerEmail)) return json({ error: "valid_payer_email_required" }, 400);
  const admin = createClient(SUPABASE_URL, secretKey, { auth: { persistSession: false } }); const tokenHash = await sha256(token); const nowIso = new Date().toISOString();
  const { data: session, error: sessionError } = await admin.from("public_checkout_sessions").select("id,tenant_id,order_id,status,expires_at").eq("order_id", orderId).eq("token_hash", tokenHash).maybeSingle(); if (sessionError) return json({ error: "checkout_session_lookup_failed" }, 500); if (!session) return json({ error: "invalid_checkout_session" }, 403); if (session.status !== "active") return json({ error: "checkout_session_not_active" }, 409); if (new Date(session.expires_at).getTime() <= Date.now()) { await admin.from("public_checkout_sessions").update({ status: "expired", updated_at: nowIso }).eq("id", session.id); return json({ error: "checkout_session_expired" }, 409); }
  const { data: order, error: orderError } = await admin.from("orders").select("id,tenant_id,operation_id,status,currency,grand_total_minor,reference_label,metadata").eq("id", orderId).eq("tenant_id", session.tenant_id).maybeSingle(); if (orderError) return json({ error: "order_lookup_failed" }, 500); if (!order) return json({ error: "order_not_found" }, 404); if (!["submitted", "confirmed"].includes(order.status)) return json({ error: "order_not_payable", status: order.status }, 409); if (order.currency !== "BRL") return json({ error: "unsupported_currency" }, 409);
  const { data: operation } = await admin.from("operations").select("code,offering_id,archived_at").eq("id", order.operation_id).maybeSingle(); if (!operation || operation.code !== CANONICAL_CIOSP_OPERATION_CODE || operation.archived_at) return json({ error: "order_not_canonical_ciops" }, 409);
  const { data: offering } = await admin.from("offerings").select("id,status,metadata").eq("id", operation.offering_id).maybeSingle(); if (!offering || offering.status !== "active") return json({ error: "offering_not_active" }, 409);
  const offeringMeta = (offering.metadata ?? {}) as Record<string, unknown>; const orderMeta = (order.metadata ?? {}) as Record<string, unknown>; const qaClosedSalesAllowed = orderMeta.qa_public_checkout === true && MP_ENVIRONMENT === "test"; if (offeringMeta.sales_public !== true && !qaClosedSalesAllowed) return json({ error: "sales_not_open" }, 409);
  const { data: facts, error: factsError } = await admin.from("financial_facts").select("fact_type,amount_minor").eq("order_id", order.id); if (factsError) return json({ error: "financial_facts_lookup_failed" }, 500); let gross = 0, reversed = 0, refunded = 0; for (const fact of facts ?? []) { const amount = Number(fact.amount_minor ?? 0); if (fact.fact_type === "PAYMENT_RECORDED") gross += amount; else if (fact.fact_type === "PAYMENT_REVERSED") reversed += amount; else if (fact.fact_type === "REFUND_RECORDED") refunded += amount; }
  const paidBefore = Math.max((gross - reversed) - refunded, 0); const total = Number(order.grand_total_minor ?? 0); const outstanding = Math.max(total - paidBefore, 0); if (!Number.isFinite(outstanding) || outstanding <= 0) return json({ error: "order_has_no_outstanding_balance" }, 409);
  const configuredEntry = Number(offeringMeta.entry_minor ?? 0); const stage = paidBefore <= 0 && configuredEntry > 0 && configuredEntry < total ? "entry" : "balance"; const amountMinor = stage === "entry" ? Math.min(configuredEntry, outstanding) : outstanding; if (!Number.isFinite(amountMinor) || amountMinor <= 0) return json({ error: "invalid_charge_amount" }, 409);
  await admin.rpc("ensure_order_reservation_for_payment", { _order_id: order.id });
  const { data: openCharges, error: openChargeError } = await admin.from("payment_charges").select("id,tenant_id,order_id,status,currency,amount_minor,external_reference,provider,provider_order_id,metadata").eq("order_id", order.id).eq("provider", "mercado_pago").in("status", ["draft", "pending", "processing"]).order("created_at", { ascending: false }).limit(10); if (openChargeError) return json({ error: "charge_lookup_failed" }, 500); let charge = (openCharges ?? []).find((c: any) => Number(c.amount_minor) === amountMinor && c?.metadata?.commercial_payment_stage === stage) ?? null;
  if (!charge) { const externalReference = `cobs_${String(order.id).replaceAll("-", "")}_${Date.now()}`; const { data: createdCharge, error: createChargeError } = await admin.from("payment_charges").insert({ tenant_id: order.tenant_id, order_id: order.id, provider: "mercado_pago", status: "draft", currency: "BRL", amount_minor: amountMinor, external_reference: externalReference, description: stage === "entry" ? "CIOSP 2027 — entrada" : "CIOSP 2027 — saldo", created_by: null, metadata: { environment: "test", source: "public_checkout", commercial_payment_stage: stage, paid_before_minor: paidBefore, entry_minor: configuredEntry } }).select("id,tenant_id,order_id,status,currency,amount_minor,external_reference,provider,provider_order_id,metadata").single(); if (createChargeError || !createdCharge) return json({ error: "charge_create_failed", details: createChargeError?.message }, 500); charge = createdCharge; }
  const { data: existingAttempt, error: attemptLookupError } = await admin.from("payment_attempts").select("*").eq("charge_id", charge.id).eq("provider", "mercado_pago").eq("method", "pix").in("status", ["created", "pending", "processing"]).order("created_at", { ascending: false }).limit(1).maybeSingle(); if (attemptLookupError) return json({ error: "attempt_lookup_failed" }, 500);
  if (existingAttempt?.provider_order_id && (existingAttempt.pix_qr_code || existingAttempt.pix_ticket_url)) return json({ order_id: order.id, charge_id: charge.id, attempt_id: existingAttempt.id, amount_minor: amountMinor, stage, status: existingAttempt.status, pix: { qr_code: existingAttempt.pix_qr_code, qr_code_base64: existingAttempt.pix_qr_code_base64, ticket_url: existingAttempt.pix_ticket_url }, reused: true, environment: "test" });
  let attempt = existingAttempt; if (!attempt) { const idempotencyKey = crypto.randomUUID(); const amount = (amountMinor / 100).toFixed(2); const requestSnapshot = { type: "online", total_amount: amount, external_reference: charge.external_reference, processing_mode: "automatic", transactions: { payments: [{ amount, payment_method: { id: "pix", type: "bank_transfer" } }] }, payer: { email: "test_user_br@testuser.com", first_name: "APRO" } }; const { data: createdAttempt, error: createAttemptError } = await admin.from("payment_attempts").insert({ tenant_id: order.tenant_id, charge_id: charge.id, provider: "mercado_pago", method: "pix", status: "created", amount_minor: amountMinor, idempotency_key: idempotencyKey, request_snapshot: requestSnapshot, metadata: { payment_method_id: "pix", environment: "test", source: "public_checkout" } }).select("*").single(); if (createAttemptError || !createdAttempt) return json({ error: "attempt_create_failed", details: createAttemptError?.message }, 500); attempt = createdAttempt; }
  let mpResponse: Response; try { mpResponse = await fetch("https://api.mercadopago.com/v1/orders", { method: "POST", headers: { accept: "application/json", "content-type": "application/json", authorization: `Bearer ${MP_TEST_ACCESS_TOKEN}`, "x-idempotency-key": attempt.idempotency_key }, body: JSON.stringify(attempt.request_snapshot) }); } catch { return json({ error: "mercado_pago_network_error", attempt_id: attempt.id }, 502); }
  const mp = await mpResponse.json().catch(() => ({})); if (!mpResponse.ok) { await admin.from("payment_attempts").update({ status: "rejected", provider_status: "request_error", response_snapshot: mp }).eq("id", attempt.id); return json({ error: "mercado_pago_error", status: mpResponse.status, attempt_id: attempt.id }, 502); }
  const payment = mp?.transactions?.payments?.[0] ?? {}; const method = payment?.payment_method ?? {}; const providerStatus = payment?.status ?? mp?.status ?? null; const providerStatusDetail = payment?.status_detail ?? mp?.status_detail ?? null; const attemptStatus = mapAttemptStatus(providerStatus, providerStatusDetail); const now = new Date().toISOString();
  await admin.from("payment_attempts").update({ status: attemptStatus, provider_order_id: mp?.id ?? null, provider_payment_id: payment?.id ?? null, provider_status: providerStatus, provider_status_detail: providerStatusDetail, pix_qr_code: method?.qr_code ?? null, pix_qr_code_base64: method?.qr_code_base64 ?? null, pix_ticket_url: method?.ticket_url ?? null, response_snapshot: mp, ...(attemptStatus === "approved" ? { approved_at: now } : {}) }).eq("id", attempt.id);
  const chargeStatus = attemptStatus === "approved" ? "paid" : attemptStatus === "processing" ? "processing" : "pending"; await admin.from("payment_charges").update({ status: chargeStatus, provider_order_id: mp?.id ?? null, ...(chargeStatus === "paid" ? { paid_amount_minor: amountMinor, paid_at: now } : {}) }).eq("id", charge.id);
  if (chargeStatus === "paid") { const { error: factError } = await admin.rpc("record_provider_payment", { _order_id: order.id, _amount_minor: amountMinor, _reference: `mercado_pago:${payment?.id ?? mp?.id}`, _reason: stage === "entry" ? "CIOSP 2027 public checkout entry approved" : "CIOSP 2027 public checkout balance approved", _occurred_at: payment?.date_approved ?? mp?.last_updated_date ?? now }); if (factError) return json({ error: "financial_fact_failed", details: factError.message }, 500); await admin.from("public_checkout_sessions").update({ status: "consumed", updated_at: now }).eq("id", session.id); }
  return json({ order_id: order.id, charge_id: charge.id, attempt_id: attempt.id, provider_order_id: mp?.id ?? null, provider_payment_id: payment?.id ?? null, amount_minor: amountMinor, stage, status: attemptStatus, pix: { qr_code: method?.qr_code ?? null, qr_code_base64: method?.qr_code_base64 ?? null, ticket_url: method?.ticket_url ?? null }, reused: false, environment: "test" }, 201);
});