import * as React from "react";
import { createFileRoute, useParams } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PanelSkeleton } from "@/components/feedback/loading";
import { feedback } from "@/components/feedback/feedback";
import { supabase } from "@/integrations/supabase/client";
import { humanizeError } from "@/lib/auth";
import { useI18n } from "@/lib/i18n";
import { useTenant } from "@/lib/tenant";

export const Route = createFileRoute("/_authenticated/operations/$operationId/costs")({ component: OperationCosts });
const db = supabase as any;
const CATEGORIES: Record<string,string> = { hotel:"Hotel", transport:"Transporte", food:"Alimentação", insurance:"Seguro", event:"Inscrição / evento", staff:"Equipe / guia", other:"Outros" };
const DOCUMENT_TYPES: Record<string,string> = { quote:"Proposta", contract:"Contrato", invoice:"Nota / fatura", receipt:"Comprovante", insurance:"Seguro", license:"Licença", other:"Outro" };
const money = (v:any) => new Intl.NumberFormat("pt-BR", { style:"currency", currency:"BRL" }).format((Number(v ?? 0) || 0)/100);
const minor = (v:string) => { const n = Number(v.replace(/\./g,"").replace(",",".")); return Number.isFinite(n) ? Math.round(n*100) : 0; };
const dateBR = (v?:string|null) => v ? new Intl.DateTimeFormat("pt-BR", { timeZone:"UTC" }).format(new Date(`${v}T12:00:00Z`)) : "—";
function Metric({label,value,note}:{label:string;value:string;note?:string}) { return <div className="surface-panel p-4"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p>{note?<p className="mt-1 text-xs text-muted-foreground">{note}</p>:null}</div>; }

function OperationCosts() {
  const { operationId } = useParams({ from:"/_authenticated/operations/$operationId/costs" });
  const { canManage } = useTenant();
  const { locale } = useI18n();
  const qc = useQueryClient();
  const [plan,setPlan] = React.useState({ passengers:"30", unitPrice:"10000", contingency:"0", taxes:"0" });
  const [quote,setQuote] = React.useState({ supplier:"", category:"hotel", description:"", amount:"", validUntil:"", cancellationTerms:"", notes:"" });
  const [installment,setInstallment] = React.useState({ quoteId:"", dueDate:"", amount:"", notes:"" });
  const [contractRef,setContractRef] = React.useState<Record<string,string>>({});
  const [document,setDocument] = React.useState({ quoteId:"", type:"quote", title:"", reference:"", issuedAt:"", expiresAt:"", notes:"" });

  const profitability = useQuery({ queryKey:["operation-profitability",operationId], queryFn: async()=>{ const {data,error}=await db.from("operation_profitability_summary").select("*").eq("operation_id",operationId).maybeSingle(); if(error) throw error; return data; } });
  const commitments = useQuery({ queryKey:["operation-commitments",operationId], queryFn: async()=>{ const {data,error}=await db.from("operation_supplier_commitment_summary").select("*").eq("operation_id",operationId).maybeSingle(); if(error) throw error; return data; } });
  const documentSummary = useQuery({ queryKey:["operation-document-summary",operationId], queryFn: async()=>{ const {data,error}=await db.from("operation_supplier_document_summary").select("*").eq("operation_id",operationId).maybeSingle(); if(error) throw error; return data; } });
  const documents = useQuery({ queryKey:["operation-documents",operationId], queryFn: async()=>{ const {data,error}=await db.from("supplier_documents").select("id,quote_id,document_type,title,reference_url,issued_at,expires_at,status,notes,created_at,quote:operation_quotes(description,category,supplier:suppliers(name))").eq("operation_id",operationId).order("created_at",{ascending:false}); if(error) throw error; return data ?? []; } });
  const planQuery = useQuery({ queryKey:["operation-financial-plan",operationId], queryFn: async()=>{ const {data,error}=await db.from("operation_financial_plans").select("*").eq("operation_id",operationId).maybeSingle(); if(error) throw error; return data; } });
  const quotes = useQuery({ queryKey:["operation-quotes",operationId], queryFn: async()=>{ const {data,error}=await db.from("operation_quotes").select("id,category,description,amount_minor,status,valid_until,cancellation_terms,notes,contract_reference,contracted_at,created_at,supplier:suppliers(name),quote_payment_schedule(id,installment_no,due_date,amount_minor,status,paid_at,notes)").eq("operation_id",operationId).order("created_at",{ascending:false}); if(error) throw error; return data ?? []; } });

  React.useEffect(()=>{ if(planQuery.data) setPlan({ passengers:String(planQuery.data.expected_paying_passengers ?? 30), unitPrice:String((planQuery.data.target_unit_price_minor ?? 0)/100), contingency:String((planQuery.data.contingency_minor ?? 0)/100), taxes:String((planQuery.data.tax_fee_minor ?? 0)/100) }); },[planQuery.data]);
  const invalidate = () => ["operation-profitability","operation-commitments","operation-document-summary","operation-documents","operation-financial-plan","operation-quotes"].forEach((k)=>void qc.invalidateQueries({queryKey:[k,operationId]}));
  const err = (e:unknown) => feedback.error(humanizeError(e,locale));

  const savePlan = useMutation({ mutationFn: async()=>{ const {data:op,error:oe}=await db.from("operations").select("tenant_id").eq("id",operationId).single(); if(oe) throw oe; const {error}=await db.from("operation_financial_plans").upsert({ tenant_id:op.tenant_id, operation_id:operationId, expected_paying_passengers:Math.max(1,Number(plan.passengers)||1), target_unit_price_minor:minor(plan.unitPrice), contingency_minor:minor(plan.contingency), tax_fee_minor:minor(plan.taxes), updated_at:new Date().toISOString() },{onConflict:"operation_id"}); if(error) throw error; }, onSuccess:()=>{feedback.success("Cenário atualizado.");invalidate();}, onError:err });
  const createQuote = useMutation({ mutationFn: async()=>{ const {error}=await db.rpc("create_operation_quote",{ _operation_id:operationId,_supplier_name:quote.supplier,_category:quote.category,_description:quote.description,_amount_minor:minor(quote.amount),_valid_until:quote.validUntil||null,_cancellation_terms:quote.cancellationTerms||null,_notes:quote.notes||null }); if(error) throw error; }, onSuccess:()=>{feedback.success("Cotação cadastrada.");setQuote({supplier:"",category:"hotel",description:"",amount:"",validUntil:"",cancellationTerms:"",notes:""});invalidate();}, onError:err });
  const selectQuote = useMutation({ mutationFn:async(id:string)=>{ const {error}=await db.rpc("select_operation_quote",{_quote_id:id}); if(error) throw error; }, onSuccess:()=>{feedback.success("Proposta selecionada.");invalidate();}, onError:err });
  const contractQuote = useMutation({ mutationFn:async(id:string)=>{ const {error}=await db.rpc("contract_operation_quote",{_quote_id:id,_contract_reference:contractRef[id]?.trim()||null,_contract_notes:null}); if(error) throw error; }, onSuccess:()=>{feedback.success("Fornecedor formalizado.");invalidate();}, onError:err });
  const addInstallment = useMutation({ mutationFn:async()=>{ const {error}=await db.rpc("add_quote_payment_installment",{_quote_id:installment.quoteId,_due_date:installment.dueDate,_amount_minor:minor(installment.amount),_notes:installment.notes||null}); if(error) throw error; }, onSuccess:()=>{feedback.success("Vencimento adicionado.");setInstallment({quoteId:"",dueDate:"",amount:"",notes:""});invalidate();}, onError:err });
  const payInstallment = useMutation({ mutationFn:async(id:string)=>{ const {error}=await db.rpc("mark_quote_payment_paid",{_schedule_id:id,_paid_at:new Date().toISOString()}); if(error) throw error; }, onSuccess:()=>{feedback.success("Pagamento baixado.");invalidate();}, onError:err });
  const addDocument = useMutation({ mutationFn:async()=>{ const {error}=await db.rpc("add_supplier_document",{_quote_id:document.quoteId,_document_type:document.type,_title:document.title,_reference_url:document.reference||null,_issued_at:document.issuedAt||null,_expires_at:document.expiresAt||null,_notes:document.notes||null}); if(error) throw error; }, onSuccess:()=>{feedback.success("Documento registrado.");setDocument({quoteId:"",type:"quote",title:"",reference:"",issuedAt:"",expiresAt:"",notes:""});invalidate();}, onError:err });
  const reviewDocument = useMutation({ mutationFn:async({id,status}:{id:string;status:"approved"|"rejected"})=>{ const {error}=await db.rpc("set_supplier_document_status",{_document_id:id,_status:status}); if(error) throw error; }, onSuccess:(_,v)=>{feedback.success(v.status==="approved"?"Documento aprovado.":"Documento rejeitado.");invalidate();}, onError:err });

  if(profitability.isLoading||commitments.isLoading||documentSummary.isLoading||documents.isLoading||quotes.isLoading||planQuery.isLoading) return <PanelSkeleton rows={5}/>;
  const summary:any=profitability.data??{}; const commitment:any=commitments.data??{}; const docsSummary:any=documentSummary.data??{}; const rows:any[]=quotes.data??[]; const docRows:any[]=documents.data??[];
  const passengers=Math.max(1,Number(summary.expected_paying_passengers??plan.passengers)||1);
  const selected=rows.filter((q)=>q.status==="selected"||q.status==="contracted");
  const payments=selected.flatMap((q)=>(q.quote_payment_schedule??[]).map((p:any)=>({...p,supplierName:q.supplier?.name??"Fornecedor",category:q.category}))).filter((p)=>p.status!=="cancelled").sort((a,b)=>String(a.due_date).localeCompare(String(b.due_date)));
  const grouped=Object.entries(rows.reduce<Record<string,any[]>>((a,q)=>{(a[q.category]??=[]).push(q);return a;},{})).map(([category,r])=>({category,rows:[...r].sort((a,b)=>Number(a.amount_minor)-Number(b.amount_minor)).slice(0,3)}));

  return <div className="space-y-6">
    <section><h2 className="text-2xl font-semibold">Custos & Cotações</h2><p className="text-sm text-muted-foreground">Cotação → decisão → contratação → pagamentos → documentos → margem.</p></section>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Receita prevista" value={money(summary.gross_revenue_minor)} note={`${summary.expected_paying_passengers??0} pagantes`}/><Metric label="Custos planejados" value={money(summary.total_planned_cost_minor)}/><Metric label="Lucro projetado" value={Number(summary.selected_cost_minor??0)>0?money(summary.projected_profit_minor):"—"}/><Metric label="Margem" value={Number(summary.selected_cost_minor??0)>0&&summary.margin_pct!=null?`${summary.margin_pct}%`:"—"}/><Metric label="Ponto de equilíbrio" value={summary.break_even_passengers?`${summary.break_even_passengers} pax`:"—"}/></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Contratado" value={money(commitment.contracted_minor)} note={`${commitment.contracted_suppliers??0} fornecedores`}/><Metric label="Pago" value={money(commitment.paid_minor)}/><Metric label="Saldo a pagar" value={money(commitment.balance_minor)}/><Metric label="Próximo vencimento" value={commitment.next_due_amount_minor?money(commitment.next_due_amount_minor):"—"} note={dateBR(commitment.next_due_date)}/><Metric label="Parcelas abertas" value={`${commitment.open_installments??0}`}/></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Documentos" value={`${docsSummary.total_documents??0}`}/><Metric label="Aprovados" value={`${docsSummary.approved_documents??0}`}/><Metric label="Pendentes" value={`${docsSummary.pending_documents??0}`}/><Metric label="Rejeitados" value={`${docsSummary.rejected_documents??0}`}/><Metric label="Validade vencida" value={`${docsSummary.overdue_expirations??0}`}/></div>

    {canManage?<section className="surface-panel space-y-4 p-5"><h3 className="font-semibold">Cenário financeiro</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><Label>Pagantes</Label><Input value={plan.passengers} onChange={(e)=>setPlan({...plan,passengers:e.target.value})}/></div><div><Label>Ticket alvo (R$)</Label><Input value={plan.unitPrice} onChange={(e)=>setPlan({...plan,unitPrice:e.target.value})}/></div><div><Label>Contingência (R$)</Label><Input value={plan.contingency} onChange={(e)=>setPlan({...plan,contingency:e.target.value})}/></div><div><Label>Taxas/impostos (R$)</Label><Input value={plan.taxes} onChange={(e)=>setPlan({...plan,taxes:e.target.value})}/></div></div><Button onClick={()=>savePlan.mutate()} disabled={savePlan.isPending}>Salvar cenário</Button></section>:null}

    {grouped.length?<section className="space-y-3"><h3 className="font-semibold">Top 3 para decisão</h3>{grouped.map(({category,rows:r})=><div key={category} className="surface-panel p-4"><h4 className="mb-3 font-semibold">{CATEGORIES[category]??category}</h4><div className="grid gap-3 lg:grid-cols-3">{r.map((q:any,i:number)=><div key={q.id} className="rounded-lg border border-border p-3"><p className="text-xs text-muted-foreground">#{i+1}</p><p className="font-semibold">{q.supplier?.name}</p><p className="text-lg font-semibold">{money(q.amount_minor)}</p><p className="text-xs text-muted-foreground">{money(Number(q.amount_minor)/passengers)} por passageiro · validade {dateBR(q.valid_until)}</p><p className="mt-1 text-xs text-muted-foreground">{q.cancellation_terms||"Cancelamento não informado"}</p>{canManage&&!["selected","contracted"].includes(q.status)?<Button className="mt-3" size="sm" variant="outline" onClick={()=>selectQuote.mutate(q.id)}>Escolher esta</Button>:null}</div>)}</div></div>)}</section>:null}

    {canManage?<section className="surface-panel space-y-4 p-5"><h3 className="font-semibold">Nova cotação</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><div><Label>Fornecedor</Label><Input value={quote.supplier} onChange={(e)=>setQuote({...quote,supplier:e.target.value})}/></div><div><Label>Categoria</Label><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={quote.category} onChange={(e)=>setQuote({...quote,category:e.target.value})}>{Object.entries(CATEGORIES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div><Label>Valor total (R$)</Label><Input value={quote.amount} onChange={(e)=>setQuote({...quote,amount:e.target.value})}/></div><div className="sm:col-span-2"><Label>Descrição</Label><Input value={quote.description} onChange={(e)=>setQuote({...quote,description:e.target.value})}/></div><div><Label>Validade</Label><Input type="date" value={quote.validUntil} onChange={(e)=>setQuote({...quote,validUntil:e.target.value})}/></div><div className="sm:col-span-2"><Label>Cancelamento</Label><Input value={quote.cancellationTerms} onChange={(e)=>setQuote({...quote,cancellationTerms:e.target.value})}/></div><div><Label>Observações</Label><Input value={quote.notes} onChange={(e)=>setQuote({...quote,notes:e.target.value})}/></div></div><Button disabled={!quote.supplier.trim()||!quote.description.trim()||minor(quote.amount)<=0||createQuote.isPending} onClick={()=>createQuote.mutate()}>Cadastrar cotação</Button></section>:null}

    <section className="space-y-3"><h3 className="font-semibold">Propostas e formalização</h3>{rows.length===0?<div className="surface-panel p-5 text-sm text-muted-foreground">Nenhuma cotação cadastrada.</div>:rows.map((q:any)=><article key={q.id} className="surface-panel space-y-3 p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{q.supplier?.name}</p><p className="text-sm text-muted-foreground">{CATEGORIES[q.category]} · {q.description}</p></div><div className="text-right"><p className="font-semibold">{money(q.amount_minor)}</p><p className="text-xs uppercase text-muted-foreground">{q.status}</p></div></div>{q.status==="selected"&&canManage?<div className="flex gap-2"><Input placeholder="Referência do contrato" value={contractRef[q.id]??""} onChange={(e)=>setContractRef({...contractRef,[q.id]:e.target.value})}/><Button onClick={()=>contractQuote.mutate(q.id)}>Formalizar fornecedor</Button></div>:null}{(q.quote_payment_schedule??[]).map((p:any)=><div key={p.id} className="flex items-center justify-between rounded-lg border border-border p-3 text-sm"><span>{p.installment_no}ª · {dateBR(p.due_date)} · {money(p.amount_minor)}</span>{canManage&&q.status==="contracted"&&!["paid","cancelled"].includes(p.status)?<Button size="sm" variant="outline" onClick={()=>payInstallment.mutate(p.id)}>Marcar como pago</Button>:<span className="text-xs uppercase text-muted-foreground">{p.status}</span>}</div>)}</article>)}</section>

    {canManage&&selected.length?<section className="surface-panel space-y-4 p-5"><h3 className="font-semibold">Adicionar vencimento</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><select className="flex h-10 rounded-md border border-input bg-background px-3 text-sm" value={installment.quoteId} onChange={(e)=>setInstallment({...installment,quoteId:e.target.value})}><option value="">Selecione a proposta</option>{selected.map((q:any)=><option key={q.id} value={q.id}>{q.supplier?.name}</option>)}</select><Input type="date" value={installment.dueDate} onChange={(e)=>setInstallment({...installment,dueDate:e.target.value})}/><Input placeholder="Valor (R$)" value={installment.amount} onChange={(e)=>setInstallment({...installment,amount:e.target.value})}/><Input placeholder="Observação" value={installment.notes} onChange={(e)=>setInstallment({...installment,notes:e.target.value})}/></div><Button disabled={!installment.quoteId||!installment.dueDate||minor(installment.amount)<=0} onClick={()=>addInstallment.mutate()}>Adicionar vencimento</Button></section>:null}

    {canManage&&rows.length?<section className="surface-panel space-y-4 p-5"><h3 className="font-semibold">Registrar documento</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><select className="flex h-10 rounded-md border border-input bg-background px-3 text-sm" value={document.quoteId} onChange={(e)=>setDocument({...document,quoteId:e.target.value})}><option value="">Selecione a proposta</option>{rows.map((q:any)=><option key={q.id} value={q.id}>{q.supplier?.name}</option>)}</select><select className="flex h-10 rounded-md border border-input bg-background px-3 text-sm" value={document.type} onChange={(e)=>setDocument({...document,type:e.target.value})}>{Object.entries(DOCUMENT_TYPES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><Input placeholder="Título" value={document.title} onChange={(e)=>setDocument({...document,title:e.target.value})}/><Input placeholder="Link / referência" value={document.reference} onChange={(e)=>setDocument({...document,reference:e.target.value})}/><Input type="date" value={document.issuedAt} onChange={(e)=>setDocument({...document,issuedAt:e.target.value})}/><Input type="date" value={document.expiresAt} onChange={(e)=>setDocument({...document,expiresAt:e.target.value})}/></div><Button disabled={!document.quoteId||!document.title.trim()} onClick={()=>addDocument.mutate()}>Registrar documento</Button></section>:null}

    <section className="space-y-3"><h3 className="font-semibold">Documentos dos fornecedores</h3>{docRows.length===0?<div className="surface-panel p-5 text-sm text-muted-foreground">Nenhum documento registrado.</div>:docRows.map((d:any)=><article key={d.id} className="surface-panel p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{d.title}</p><p className="text-sm text-muted-foreground">{d.quote?.supplier?.name??"Fornecedor"} · {DOCUMENT_TYPES[d.document_type]??d.document_type} · validade {dateBR(d.expires_at)}</p></div><span className="text-xs uppercase text-muted-foreground">{d.status}</span></div>{canManage&&!["approved","rejected"].includes(d.status)?<div className="mt-3 flex gap-2"><Button size="sm" onClick={()=>reviewDocument.mutate({id:d.id,status:"approved"})}>Aprovar</Button><Button size="sm" variant="outline" onClick={()=>reviewDocument.mutate({id:d.id,status:"rejected"})}>Rejeitar</Button></div>:null}</article>)}</section>

    <section className="space-y-3"><h3 className="font-semibold">Calendário de desembolsos</h3>{payments.length===0?<div className="surface-panel p-5 text-sm text-muted-foreground">Nenhum pagamento programado.</div>:<div className="surface-panel divide-y divide-border">{payments.map((p:any)=><div key={p.id} className="grid gap-2 px-4 py-3 text-sm sm:grid-cols-[120px_1fr_160px_100px]"><span>{dateBR(p.due_date)}</span><span>{p.supplierName} · {CATEGORIES[p.category]}</span><span className="font-semibold sm:text-right">{money(p.amount_minor)}</span><span className="text-xs uppercase text-muted-foreground sm:text-right">{p.status}</span></div>)}</div>}</section>
  </div>;
}
