/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedMyRouteImport } from './routes/_authenticated/my'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedCommerceIndexRouteImport } from './routes/_authenticated/commerce.index'
import { Route as AuthenticatedCommerceOrderIdRouteImport } from './routes/_authenticated/commerce.$orderId'
import { Route as AuthenticatedExperiencesIndexRouteImport } from './routes/_authenticated/experiences.index'
import { Route as AuthenticatedExperiencesExperienceIdRouteImport } from './routes/_authenticated/experiences.$experienceId'
import { Route as AuthenticatedInviteTokenRouteImport } from './routes/_authenticated/invite.$token'
import { Route as AuthenticatedMyIndexRouteImport } from './routes/_authenticated/my.index'
import { Route as AuthenticatedMyOperationIdRouteImport } from './routes/_authenticated/my.$operationId'
import { Route as AuthenticatedOperationsIndexRouteImport } from './routes/_authenticated/operations.index'
import { Route as AuthenticatedOperationsOperationIdRouteImport } from './routes/_authenticated/operations.$operationId'
import { Route as AuthenticatedSettingsCatalogRouteImport } from './routes/_authenticated/settings_.catalog'
import { Route as AuthenticatedSettingsFleetRouteImport } from './routes/_authenticated/settings_.fleet'
import { Route as AuthenticatedSettingsPropertiesRouteImport } from './routes/_authenticated/settings_.properties'
import { Route as AuthenticatedSettingsVenuesRouteImport } from './routes/_authenticated/settings_.venues'
import { Route as AuthenticatedMyOperationIdIndexRouteImport } from './routes/_authenticated/my.$operationId.index'
import { Route as AuthenticatedMyOperationIdEventsRouteImport } from './routes/_authenticated/my.$operationId.events'
import { Route as AuthenticatedMyOperationIdJourneyRouteImport } from './routes/_authenticated/my.$operationId.journey'
import { Route as AuthenticatedMyOperationIdMessagesRouteImport } from './routes/_authenticated/my.$operationId.messages'
import { Route as AuthenticatedMyOperationIdMobilityRouteImport } from './routes/_authenticated/my.$operationId.mobility'
import { Route as AuthenticatedMyOperationIdStayRouteImport } from './routes/_authenticated/my.$operationId.stay'
import { Route as AuthenticatedOperationsOperationIdIndexRouteImport } from './routes/_authenticated/operations.$operationId.index'
import { Route as AuthenticatedOperationsOperationIdCommunicationRouteImport } from './routes/_authenticated/operations.$operationId.communication'
import { Route as AuthenticatedOperationsOperationIdEventsRouteImport } from './routes/_authenticated/operations.$operationId.events'
import { Route as AuthenticatedOperationsOperationIdHospitalityRouteImport } from './routes/_authenticated/operations.$operationId.hospitality'
import { Route as AuthenticatedOperationsOperationIdJourneyRouteImport } from './routes/_authenticated/operations.$operationId.journey'
import { Route as AuthenticatedOperationsOperationIdLiveRouteImport } from './routes/_authenticated/operations.$operationId.live'
import { Route as AuthenticatedOperationsOperationIdMobilityRouteImport } from './routes/_authenticated/operations.$operationId.mobility'
import { Route as AuthenticatedOperationsOperationIdPeopleRouteImport } from './routes/_authenticated/operations.$operationId.people'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyRoute = AuthenticatedMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommerceIndexRoute =
  AuthenticatedCommerceIndexRouteImport.update({
    id: '/commerce/',
    path: '/commerce/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommerceOrderIdRoute =
  AuthenticatedCommerceOrderIdRouteImport.update({
    id: '/commerce/$orderId',
    path: '/commerce/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExperiencesIndexRoute =
  AuthenticatedExperiencesIndexRouteImport.update({
    id: '/experiences/',
    path: '/experiences/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExperiencesExperienceIdRoute =
  AuthenticatedExperiencesExperienceIdRouteImport.update({
    id: '/experiences/$experienceId',
    path: '/experiences/$experienceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInviteTokenRoute =
  AuthenticatedInviteTokenRouteImport.update({
    id: '/invite/$token',
    path: '/invite/$token',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyIndexRoute = AuthenticatedMyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMyRoute,
} as any)
const AuthenticatedMyOperationIdRoute =
  AuthenticatedMyOperationIdRouteImport.update({
    id: '/$operationId',
    path: '/$operationId',
    getParentRoute: () => AuthenticatedMyRoute,
  } as any)
const AuthenticatedOperationsIndexRoute =
  AuthenticatedOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsOperationIdRoute =
  AuthenticatedOperationsOperationIdRouteImport.update({
    id: '/operations/$operationId',
    path: '/operations/$operationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCatalogRoute =
  AuthenticatedSettingsCatalogRouteImport.update({
    id: '/settings_/catalog',
    path: '/settings/catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsFleetRoute =
  AuthenticatedSettingsFleetRouteImport.update({
    id: '/settings_/fleet',
    path: '/settings/fleet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPropertiesRoute =
  AuthenticatedSettingsPropertiesRouteImport.update({
    id: '/settings_/properties',
    path: '/settings/properties',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsVenuesRoute =
  AuthenticatedSettingsVenuesRouteImport.update({
    id: '/settings_/venues',
    path: '/settings/venues',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyOperationIdIndexRoute =
  AuthenticatedMyOperationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMyOperationIdRoute,
  } as any)
const AuthenticatedMyOperationIdEventsRoute =
  AuthenticatedMyOperationIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedMyOperationIdRoute,
  } as any)
const AuthenticatedMyOperationIdJourneyRoute =
  AuthenticatedMyOperationIdJourneyRouteImport.update({
    id: '/journey',
    path: '/journey',
    getParentRoute: () => AuthenticatedMyOperationIdRoute,
  } as any)
const AuthenticatedMyOperationIdMessagesRoute =
  AuthenticatedMyOperationIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedMyOperationIdRoute,
  } as any)
const AuthenticatedMyOperationIdMobilityRoute =
  AuthenticatedMyOperationIdMobilityRouteImport.update({
    id: '/mobility',
    path: '/mobility',
    getParentRoute: () => AuthenticatedMyOperationIdRoute,
  } as any)
const AuthenticatedMyOperationIdStayRoute =
  AuthenticatedMyOperationIdStayRouteImport.update({
    id: '/stay',
    path: '/stay',
    getParentRoute: () => AuthenticatedMyOperationIdRoute,
  } as any)
const AuthenticatedOperationsOperationIdIndexRoute =
  AuthenticatedOperationsOperationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOperationsOperationIdRoute,
  } as any)
const AuthenticatedOperationsOperationIdCommunicationRoute =
  AuthenticatedOperationsOperationIdCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => AuthenticatedOperationsOperationIdRoute,
  } as any)
const AuthenticatedOperationsOperationIdEventsRoute =
  AuthenticatedOperationsOperationIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedOperationsOperationIdRoute,
  } as any)
const AuthenticatedOperationsOperationIdHospitalityRoute =
  AuthenticatedOperationsOperationIdHospitalityRouteImport.update({
    id: '/hospitality',
    path: '/hospitality',
    getParentRoute: () => AuthenticatedOperationsOperationIdRoute,
  } as any)
const AuthenticatedOperationsOperationIdJourneyRoute =
  AuthenticatedOperationsOperationIdJourneyRouteImport.update({
    id: '/journey',
    path: '/journey',
    getParentRoute: () => AuthenticatedOperationsOperationIdRoute,
  } as any)
const AuthenticatedOperationsOperationIdLiveRoute =
  AuthenticatedOperationsOperationIdLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AuthenticatedOperationsOperationIdRoute,
  } as any)
const AuthenticatedOperationsOperationIdMobilityRoute =
  AuthenticatedOperationsOperationIdMobilityRouteImport.update({
    id: '/mobility',
    path: '/mobility',
    getParentRoute: () => AuthenticatedOperationsOperationIdRoute,
  } as any)
const AuthenticatedOperationsOperationIdPeopleRoute =
  AuthenticatedOperationsOperationIdPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedOperationsOperationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/my': typeof AuthenticatedMyRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/commerce/$orderId': typeof AuthenticatedCommerceOrderIdRoute
  '/experiences/$experienceId': typeof AuthenticatedExperiencesExperienceIdRoute
  '/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/my/$operationId': typeof AuthenticatedMyOperationIdRouteWithChildren
  '/operations/$operationId': typeof AuthenticatedOperationsOperationIdRouteWithChildren
  '/settings/catalog': typeof AuthenticatedSettingsCatalogRoute
  '/settings/fleet': typeof AuthenticatedSettingsFleetRoute
  '/settings/properties': typeof AuthenticatedSettingsPropertiesRoute
  '/settings/venues': typeof AuthenticatedSettingsVenuesRoute
  '/commerce/': typeof AuthenticatedCommerceIndexRoute
  '/experiences/': typeof AuthenticatedExperiencesIndexRoute
  '/my/': typeof AuthenticatedMyIndexRoute
  '/operations/': typeof AuthenticatedOperationsIndexRoute
  '/my/$operationId/events': typeof AuthenticatedMyOperationIdEventsRoute
  '/my/$operationId/journey': typeof AuthenticatedMyOperationIdJourneyRoute
  '/my/$operationId/messages': typeof AuthenticatedMyOperationIdMessagesRoute
  '/my/$operationId/mobility': typeof AuthenticatedMyOperationIdMobilityRoute
  '/my/$operationId/stay': typeof AuthenticatedMyOperationIdStayRoute
  '/operations/$operationId/communication': typeof AuthenticatedOperationsOperationIdCommunicationRoute
  '/operations/$operationId/events': typeof AuthenticatedOperationsOperationIdEventsRoute
  '/operations/$operationId/hospitality': typeof AuthenticatedOperationsOperationIdHospitalityRoute
  '/operations/$operationId/journey': typeof AuthenticatedOperationsOperationIdJourneyRoute
  '/operations/$operationId/live': typeof AuthenticatedOperationsOperationIdLiveRoute
  '/operations/$operationId/mobility': typeof AuthenticatedOperationsOperationIdMobilityRoute
  '/operations/$operationId/people': typeof AuthenticatedOperationsOperationIdPeopleRoute
  '/my/$operationId/': typeof AuthenticatedMyOperationIdIndexRoute
  '/operations/$operationId/': typeof AuthenticatedOperationsOperationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/commerce/$orderId': typeof AuthenticatedCommerceOrderIdRoute
  '/experiences/$experienceId': typeof AuthenticatedExperiencesExperienceIdRoute
  '/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/settings/catalog': typeof AuthenticatedSettingsCatalogRoute
  '/settings/fleet': typeof AuthenticatedSettingsFleetRoute
  '/settings/properties': typeof AuthenticatedSettingsPropertiesRoute
  '/settings/venues': typeof AuthenticatedSettingsVenuesRoute
  '/commerce': typeof AuthenticatedCommerceIndexRoute
  '/experiences': typeof AuthenticatedExperiencesIndexRoute
  '/my': typeof AuthenticatedMyIndexRoute
  '/operations': typeof AuthenticatedOperationsIndexRoute
  '/my/$operationId/events': typeof AuthenticatedMyOperationIdEventsRoute
  '/my/$operationId/journey': typeof AuthenticatedMyOperationIdJourneyRoute
  '/my/$operationId/messages': typeof AuthenticatedMyOperationIdMessagesRoute
  '/my/$operationId/mobility': typeof AuthenticatedMyOperationIdMobilityRoute
  '/my/$operationId/stay': typeof AuthenticatedMyOperationIdStayRoute
  '/operations/$operationId/communication': typeof AuthenticatedOperationsOperationIdCommunicationRoute
  '/operations/$operationId/events': typeof AuthenticatedOperationsOperationIdEventsRoute
  '/operations/$operationId/hospitality': typeof AuthenticatedOperationsOperationIdHospitalityRoute
  '/operations/$operationId/journey': typeof AuthenticatedOperationsOperationIdJourneyRoute
  '/operations/$operationId/live': typeof AuthenticatedOperationsOperationIdLiveRoute
  '/operations/$operationId/mobility': typeof AuthenticatedOperationsOperationIdMobilityRoute
  '/operations/$operationId/people': typeof AuthenticatedOperationsOperationIdPeopleRoute
  '/my/$operationId': typeof AuthenticatedMyOperationIdIndexRoute
  '/operations/$operationId': typeof AuthenticatedOperationsOperationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/my': typeof AuthenticatedMyRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/commerce/$orderId': typeof AuthenticatedCommerceOrderIdRoute
  '/_authenticated/experiences/$experienceId': typeof AuthenticatedExperiencesExperienceIdRoute
  '/_authenticated/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/_authenticated/my/$operationId': typeof AuthenticatedMyOperationIdRouteWithChildren
  '/_authenticated/operations/$operationId': typeof AuthenticatedOperationsOperationIdRouteWithChildren
  '/_authenticated/settings_/catalog': typeof AuthenticatedSettingsCatalogRoute
  '/_authenticated/settings_/fleet': typeof AuthenticatedSettingsFleetRoute
  '/_authenticated/settings_/properties': typeof AuthenticatedSettingsPropertiesRoute
  '/_authenticated/settings_/venues': typeof AuthenticatedSettingsVenuesRoute
  '/_authenticated/commerce/': typeof AuthenticatedCommerceIndexRoute
  '/_authenticated/experiences/': typeof AuthenticatedExperiencesIndexRoute
  '/_authenticated/my/': typeof AuthenticatedMyIndexRoute
  '/_authenticated/operations/': typeof AuthenticatedOperationsIndexRoute
  '/_authenticated/my/$operationId/events': typeof AuthenticatedMyOperationIdEventsRoute
  '/_authenticated/my/$operationId/journey': typeof AuthenticatedMyOperationIdJourneyRoute
  '/_authenticated/my/$operationId/messages': typeof AuthenticatedMyOperationIdMessagesRoute
  '/_authenticated/my/$operationId/mobility': typeof AuthenticatedMyOperationIdMobilityRoute
  '/_authenticated/my/$operationId/stay': typeof AuthenticatedMyOperationIdStayRoute
  '/_authenticated/operations/$operationId/communication': typeof AuthenticatedOperationsOperationIdCommunicationRoute
  '/_authenticated/operations/$operationId/events': typeof AuthenticatedOperationsOperationIdEventsRoute
  '/_authenticated/operations/$operationId/hospitality': typeof AuthenticatedOperationsOperationIdHospitalityRoute
  '/_authenticated/operations/$operationId/journey': typeof AuthenticatedOperationsOperationIdJourneyRoute
  '/_authenticated/operations/$operationId/live': typeof AuthenticatedOperationsOperationIdLiveRoute
  '/_authenticated/operations/$operationId/mobility': typeof AuthenticatedOperationsOperationIdMobilityRoute
  '/_authenticated/operations/$operationId/people': typeof AuthenticatedOperationsOperationIdPeopleRoute
  '/_authenticated/my/$operationId/': typeof AuthenticatedMyOperationIdIndexRoute
  '/_authenticated/operations/$operationId/': typeof AuthenticatedOperationsOperationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/inbox'
    | '/my'
    | '/onboarding'
    | '/people'
    | '/settings'
    | '/team'
    | '/commerce/$orderId'
    | '/experiences/$experienceId'
    | '/invite/$token'
    | '/my/$operationId'
    | '/operations/$operationId'
    | '/settings/catalog'
    | '/settings/fleet'
    | '/settings/properties'
    | '/settings/venues'
    | '/commerce/'
    | '/experiences/'
    | '/my/'
    | '/operations/'
    | '/my/$operationId/events'
    | '/my/$operationId/journey'
    | '/my/$operationId/messages'
    | '/my/$operationId/mobility'
    | '/my/$operationId/stay'
    | '/operations/$operationId/communication'
    | '/operations/$operationId/events'
    | '/operations/$operationId/hospitality'
    | '/operations/$operationId/journey'
    | '/operations/$operationId/live'
    | '/operations/$operationId/mobility'
    | '/operations/$operationId/people'
    | '/my/$operationId/'
    | '/operations/$operationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/inbox'
    | '/onboarding'
    | '/people'
    | '/settings'
    | '/team'
    | '/commerce/$orderId'
    | '/experiences/$experienceId'
    | '/invite/$token'
    | '/settings/catalog'
    | '/settings/fleet'
    | '/settings/properties'
    | '/settings/venues'
    | '/commerce'
    | '/experiences'
    | '/my'
    | '/operations'
    | '/my/$operationId/events'
    | '/my/$operationId/journey'
    | '/my/$operationId/messages'
    | '/my/$operationId/mobility'
    | '/my/$operationId/stay'
    | '/operations/$operationId/communication'
    | '/operations/$operationId/events'
    | '/operations/$operationId/hospitality'
    | '/operations/$operationId/journey'
    | '/operations/$operationId/live'
    | '/operations/$operationId/mobility'
    | '/operations/$operationId/people'
    | '/my/$operationId'
    | '/operations/$operationId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/inbox'
    | '/_authenticated/my'
    | '/_authenticated/onboarding'
    | '/_authenticated/people'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/commerce/$orderId'
    | '/_authenticated/experiences/$experienceId'
    | '/_authenticated/invite/$token'
    | '/_authenticated/my/$operationId'
    | '/_authenticated/operations/$operationId'
    | '/_authenticated/settings_/catalog'
    | '/_authenticated/settings_/fleet'
    | '/_authenticated/settings_/properties'
    | '/_authenticated/settings_/venues'
    | '/_authenticated/commerce/'
    | '/_authenticated/experiences/'
    | '/_authenticated/my/'
    | '/_authenticated/operations/'
    | '/_authenticated/my/$operationId/events'
    | '/_authenticated/my/$operationId/journey'
    | '/_authenticated/my/$operationId/messages'
    | '/_authenticated/my/$operationId/mobility'
    | '/_authenticated/my/$operationId/stay'
    | '/_authenticated/operations/$operationId/communication'
    | '/_authenticated/operations/$operationId/events'
    | '/_authenticated/operations/$operationId/hospitality'
    | '/_authenticated/operations/$operationId/journey'
    | '/_authenticated/operations/$operationId/live'
    | '/_authenticated/operations/$operationId/mobility'
    | '/_authenticated/operations/$operationId/people'
    | '/_authenticated/my/$operationId/'
    | '/_authenticated/operations/$operationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my': {
      id: '/_authenticated/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthenticatedMyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commerce/': {
      id: '/_authenticated/commerce/'
      path: '/commerce'
      fullPath: '/commerce/'
      preLoaderRoute: typeof AuthenticatedCommerceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commerce/$orderId': {
      id: '/_authenticated/commerce/$orderId'
      path: '/commerce/$orderId'
      fullPath: '/commerce/$orderId'
      preLoaderRoute: typeof AuthenticatedCommerceOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiences/': {
      id: '/_authenticated/experiences/'
      path: '/experiences'
      fullPath: '/experiences/'
      preLoaderRoute: typeof AuthenticatedExperiencesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiences/$experienceId': {
      id: '/_authenticated/experiences/$experienceId'
      path: '/experiences/$experienceId'
      fullPath: '/experiences/$experienceId'
      preLoaderRoute: typeof AuthenticatedExperiencesExperienceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invite/$token': {
      id: '/_authenticated/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AuthenticatedInviteTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my/': {
      id: '/_authenticated/my/'
      path: '/'
      fullPath: '/my/'
      preLoaderRoute: typeof AuthenticatedMyIndexRouteImport
      parentRoute: typeof AuthenticatedMyRoute
    }
    '/_authenticated/my/$operationId': {
      id: '/_authenticated/my/$operationId'
      path: '/$operationId'
      fullPath: '/my/$operationId'
      preLoaderRoute: typeof AuthenticatedMyOperationIdRouteImport
      parentRoute: typeof AuthenticatedMyRoute
    }
    '/_authenticated/operations/': {
      id: '/_authenticated/operations/'
      path: '/operations'
      fullPath: '/operations/'
      preLoaderRoute: typeof AuthenticatedOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations/$operationId': {
      id: '/_authenticated/operations/$operationId'
      path: '/operations/$operationId'
      fullPath: '/operations/$operationId'
      preLoaderRoute: typeof AuthenticatedOperationsOperationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings_/catalog': {
      id: '/_authenticated/settings_/catalog'
      path: '/settings/catalog'
      fullPath: '/settings/catalog'
      preLoaderRoute: typeof AuthenticatedSettingsCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings_/fleet': {
      id: '/_authenticated/settings_/fleet'
      path: '/settings/fleet'
      fullPath: '/settings/fleet'
      preLoaderRoute: typeof AuthenticatedSettingsFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings_/properties': {
      id: '/_authenticated/settings_/properties'
      path: '/settings/properties'
      fullPath: '/settings/properties'
      preLoaderRoute: typeof AuthenticatedSettingsPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings_/venues': {
      id: '/_authenticated/settings_/venues'
      path: '/settings/venues'
      fullPath: '/settings/venues'
      preLoaderRoute: typeof AuthenticatedSettingsVenuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my/$operationId/': {
      id: '/_authenticated/my/$operationId/'
      path: '/'
      fullPath: '/my/$operationId/'
      preLoaderRoute: typeof AuthenticatedMyOperationIdIndexRouteImport
      parentRoute: typeof AuthenticatedMyOperationIdRoute
    }
    '/_authenticated/my/$operationId/events': {
      id: '/_authenticated/my/$operationId/events'
      path: '/events'
      fullPath: '/my/$operationId/events'
      preLoaderRoute: typeof AuthenticatedMyOperationIdEventsRouteImport
      parentRoute: typeof AuthenticatedMyOperationIdRoute
    }
    '/_authenticated/my/$operationId/journey': {
      id: '/_authenticated/my/$operationId/journey'
      path: '/journey'
      fullPath: '/my/$operationId/journey'
      preLoaderRoute: typeof AuthenticatedMyOperationIdJourneyRouteImport
      parentRoute: typeof AuthenticatedMyOperationIdRoute
    }
    '/_authenticated/my/$operationId/messages': {
      id: '/_authenticated/my/$operationId/messages'
      path: '/messages'
      fullPath: '/my/$operationId/messages'
      preLoaderRoute: typeof AuthenticatedMyOperationIdMessagesRouteImport
      parentRoute: typeof AuthenticatedMyOperationIdRoute
    }
    '/_authenticated/my/$operationId/mobility': {
      id: '/_authenticated/my/$operationId/mobility'
      path: '/mobility'
      fullPath: '/my/$operationId/mobility'
      preLoaderRoute: typeof AuthenticatedMyOperationIdMobilityRouteImport
      parentRoute: typeof AuthenticatedMyOperationIdRoute
    }
    '/_authenticated/my/$operationId/stay': {
      id: '/_authenticated/my/$operationId/stay'
      path: '/stay'
      fullPath: '/my/$operationId/stay'
      preLoaderRoute: typeof AuthenticatedMyOperationIdStayRouteImport
      parentRoute: typeof AuthenticatedMyOperationIdRoute
    }
    '/_authenticated/operations/$operationId/': {
      id: '/_authenticated/operations/$operationId/'
      path: '/'
      fullPath: '/operations/$operationId/'
      preLoaderRoute: typeof AuthenticatedOperationsOperationIdIndexRouteImport
      parentRoute: typeof AuthenticatedOperationsOperationIdRoute
    }
    '/_authenticated/operations/$operationId/communication': {
      id: '/_authenticated/operations/$operationId/communication'
      path: '/communication'
      fullPath: '/operations/$operationId/communication'
      preLoaderRoute: typeof AuthenticatedOperationsOperationIdCommunicationRouteImport
      parentRoute: typeof AuthenticatedOperationsOperationIdRoute
    }
    '/_authenticated/operations/$operationId/events': {
      id: '/_authenticated/operations/$operationId/events'
      path: '/events'
      fullPath: '/operations/$operationId/events'
      preLoaderRoute: typeof AuthenticatedOperationsOperationIdEventsRouteImport
      parentRoute: typeof AuthenticatedOperationsOperationIdRoute
    }
    '/_authenticated/operations/$operationId/hospitality': {
      id: '/_authenticated/operations/$operationId/hospitality'
      path: '/hospitality'
      fullPath: '/operations/$operationId/hospitality'
      preLoaderRoute: typeof AuthenticatedOperationsOperationIdHospitalityRouteImport
      parentRoute: typeof AuthenticatedOperationsOperationIdRoute
    }
    '/_authenticated/operations/$operationId/journey': {
      id: '/_authenticated/operations/$operationId/journey'
      path: '/journey'
      fullPath: '/operations/$operationId/journey'
      preLoaderRoute: typeof AuthenticatedOperationsOperationIdJourneyRouteImport
      parentRoute: typeof AuthenticatedOperationsOperationIdRoute
    }
    '/_authenticated/operations/$operationId/live': {
      id: '/_authenticated/operations/$operationId/live'
      path: '/live'
      fullPath: '/operations/$operationId/live'
      preLoaderRoute: typeof AuthenticatedOperationsOperationIdLiveRouteImport
      parentRoute: typeof AuthenticatedOperationsOperationIdRoute
    }
    '/_authenticated/operations/$operationId/mobility': {
      id: '/_authenticated/operations/$operationId/mobility'
      path: '/mobility'
      fullPath: '/operations/$operationId/mobility'
      preLoaderRoute: typeof AuthenticatedOperationsOperationIdMobilityRouteImport
      parentRoute: typeof AuthenticatedOperationsOperationIdRoute
    }
    '/_authenticated/operations/$operationId/people': {
      id: '/_authenticated/operations/$operationId/people'
      path: '/people'
      fullPath: '/operations/$operationId/people'
      preLoaderRoute: typeof AuthenticatedOperationsOperationIdPeopleRouteImport
      parentRoute: typeof AuthenticatedOperationsOperationIdRoute
    }
  }
}

interface AuthenticatedMyOperationIdRouteChildren {
  AuthenticatedMyOperationIdEventsRoute: typeof AuthenticatedMyOperationIdEventsRoute
  AuthenticatedMyOperationIdJourneyRoute: typeof AuthenticatedMyOperationIdJourneyRoute
  AuthenticatedMyOperationIdMessagesRoute: typeof AuthenticatedMyOperationIdMessagesRoute
  AuthenticatedMyOperationIdMobilityRoute: typeof AuthenticatedMyOperationIdMobilityRoute
  AuthenticatedMyOperationIdStayRoute: typeof AuthenticatedMyOperationIdStayRoute
  AuthenticatedMyOperationIdIndexRoute: typeof AuthenticatedMyOperationIdIndexRoute
}

const AuthenticatedMyOperationIdRouteChildren: AuthenticatedMyOperationIdRouteChildren =
  {
    AuthenticatedMyOperationIdEventsRoute:
      AuthenticatedMyOperationIdEventsRoute,
    AuthenticatedMyOperationIdJourneyRoute:
      AuthenticatedMyOperationIdJourneyRoute,
    AuthenticatedMyOperationIdMessagesRoute:
      AuthenticatedMyOperationIdMessagesRoute,
    AuthenticatedMyOperationIdMobilityRoute:
      AuthenticatedMyOperationIdMobilityRoute,
    AuthenticatedMyOperationIdStayRoute: AuthenticatedMyOperationIdStayRoute,
    AuthenticatedMyOperationIdIndexRoute: AuthenticatedMyOperationIdIndexRoute,
  }

const AuthenticatedMyOperationIdRouteWithChildren =
  AuthenticatedMyOperationIdRoute._addFileChildren(
    AuthenticatedMyOperationIdRouteChildren,
  )

interface AuthenticatedMyRouteChildren {
  AuthenticatedMyOperationIdRoute: typeof AuthenticatedMyOperationIdRouteWithChildren
  AuthenticatedMyIndexRoute: typeof AuthenticatedMyIndexRoute
}

const AuthenticatedMyRouteChildren: AuthenticatedMyRouteChildren = {
  AuthenticatedMyOperationIdRoute: AuthenticatedMyOperationIdRouteWithChildren,
  AuthenticatedMyIndexRoute: AuthenticatedMyIndexRoute,
}

const AuthenticatedMyRouteWithChildren = AuthenticatedMyRoute._addFileChildren(
  AuthenticatedMyRouteChildren,
)

interface AuthenticatedOperationsOperationIdRouteChildren {
  AuthenticatedOperationsOperationIdCommunicationRoute: typeof AuthenticatedOperationsOperationIdCommunicationRoute
  AuthenticatedOperationsOperationIdEventsRoute: typeof AuthenticatedOperationsOperationIdEventsRoute
  AuthenticatedOperationsOperationIdHospitalityRoute: typeof AuthenticatedOperationsOperationIdHospitalityRoute
  AuthenticatedOperationsOperationIdJourneyRoute: typeof AuthenticatedOperationsOperationIdJourneyRoute
  AuthenticatedOperationsOperationIdLiveRoute: typeof AuthenticatedOperationsOperationIdLiveRoute
  AuthenticatedOperationsOperationIdMobilityRoute: typeof AuthenticatedOperationsOperationIdMobilityRoute
  AuthenticatedOperationsOperationIdPeopleRoute: typeof AuthenticatedOperationsOperationIdPeopleRoute
  AuthenticatedOperationsOperationIdIndexRoute: typeof AuthenticatedOperationsOperationIdIndexRoute
}

const AuthenticatedOperationsOperationIdRouteChildren: AuthenticatedOperationsOperationIdRouteChildren =
  {
    AuthenticatedOperationsOperationIdCommunicationRoute:
      AuthenticatedOperationsOperationIdCommunicationRoute,
    AuthenticatedOperationsOperationIdEventsRoute:
      AuthenticatedOperationsOperationIdEventsRoute,
    AuthenticatedOperationsOperationIdHospitalityRoute:
      AuthenticatedOperationsOperationIdHospitalityRoute,
    AuthenticatedOperationsOperationIdJourneyRoute:
      AuthenticatedOperationsOperationIdJourneyRoute,
    AuthenticatedOperationsOperationIdLiveRoute:
      AuthenticatedOperationsOperationIdLiveRoute,
    AuthenticatedOperationsOperationIdMobilityRoute:
      AuthenticatedOperationsOperationIdMobilityRoute,
    AuthenticatedOperationsOperationIdPeopleRoute:
      AuthenticatedOperationsOperationIdPeopleRoute,
    AuthenticatedOperationsOperationIdIndexRoute:
      AuthenticatedOperationsOperationIdIndexRoute,
  }

const AuthenticatedOperationsOperationIdRouteWithChildren =
  AuthenticatedOperationsOperationIdRoute._addFileChildren(
    AuthenticatedOperationsOperationIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedMyRoute: typeof AuthenticatedMyRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedCommerceOrderIdRoute: typeof AuthenticatedCommerceOrderIdRoute
  AuthenticatedExperiencesExperienceIdRoute: typeof AuthenticatedExperiencesExperienceIdRoute
  AuthenticatedInviteTokenRoute: typeof AuthenticatedInviteTokenRoute
  AuthenticatedOperationsOperationIdRoute: typeof AuthenticatedOperationsOperationIdRouteWithChildren
  AuthenticatedSettingsCatalogRoute: typeof AuthenticatedSettingsCatalogRoute
  AuthenticatedSettingsFleetRoute: typeof AuthenticatedSettingsFleetRoute
  AuthenticatedSettingsPropertiesRoute: typeof AuthenticatedSettingsPropertiesRoute
  AuthenticatedSettingsVenuesRoute: typeof AuthenticatedSettingsVenuesRoute
  AuthenticatedCommerceIndexRoute: typeof AuthenticatedCommerceIndexRoute
  AuthenticatedExperiencesIndexRoute: typeof AuthenticatedExperiencesIndexRoute
  AuthenticatedOperationsIndexRoute: typeof AuthenticatedOperationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedMyRoute: AuthenticatedMyRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedCommerceOrderIdRoute: AuthenticatedCommerceOrderIdRoute,
  AuthenticatedExperiencesExperienceIdRoute:
    AuthenticatedExperiencesExperienceIdRoute,
  AuthenticatedInviteTokenRoute: AuthenticatedInviteTokenRoute,
  AuthenticatedOperationsOperationIdRoute:
    AuthenticatedOperationsOperationIdRouteWithChildren,
  AuthenticatedSettingsCatalogRoute: AuthenticatedSettingsCatalogRoute,
  AuthenticatedSettingsFleetRoute: AuthenticatedSettingsFleetRoute,
  AuthenticatedSettingsPropertiesRoute: AuthenticatedSettingsPropertiesRoute,
  AuthenticatedSettingsVenuesRoute: AuthenticatedSettingsVenuesRoute,
  AuthenticatedCommerceIndexRoute: AuthenticatedCommerceIndexRoute,
  AuthenticatedExperiencesIndexRoute: AuthenticatedExperiencesIndexRoute,
  AuthenticatedOperationsIndexRoute: AuthenticatedOperationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
