/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedExperiencesIndexRouteImport } from './routes/_authenticated/experiences.index'
import { Route as AuthenticatedExperiencesExperienceIdRouteImport } from './routes/_authenticated/experiences.$experienceId'
import { Route as AuthenticatedInviteTokenRouteImport } from './routes/_authenticated/invite.$token'
import { Route as AuthenticatedOperationsIndexRouteImport } from './routes/_authenticated/operations.index'
import { Route as AuthenticatedOperationsOperationIdRouteImport } from './routes/_authenticated/operations.$operationId'
import { Route as AuthenticatedOperationsOperationIdIndexRouteImport } from './routes/_authenticated/operations.$operationId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExperiencesIndexRoute =
  AuthenticatedExperiencesIndexRouteImport.update({
    id: '/experiences/',
    path: '/experiences/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExperiencesExperienceIdRoute =
  AuthenticatedExperiencesExperienceIdRouteImport.update({
    id: '/experiences/$experienceId',
    path: '/experiences/$experienceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInviteTokenRoute =
  AuthenticatedInviteTokenRouteImport.update({
    id: '/invite/$token',
    path: '/invite/$token',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsIndexRoute =
  AuthenticatedOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsOperationIdRoute =
  AuthenticatedOperationsOperationIdRouteImport.update({
    id: '/operations/$operationId',
    path: '/operations/$operationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsOperationIdIndexRoute =
  AuthenticatedOperationsOperationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOperationsOperationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/experiences/$experienceId': typeof AuthenticatedExperiencesExperienceIdRoute
  '/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/operations/$operationId': typeof AuthenticatedOperationsOperationIdRouteWithChildren
  '/experiences/': typeof AuthenticatedExperiencesIndexRoute
  '/operations/': typeof AuthenticatedOperationsIndexRoute
  '/operations/$operationId/': typeof AuthenticatedOperationsOperationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/experiences/$experienceId': typeof AuthenticatedExperiencesExperienceIdRoute
  '/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/experiences': typeof AuthenticatedExperiencesIndexRoute
  '/operations': typeof AuthenticatedOperationsIndexRoute
  '/operations/$operationId': typeof AuthenticatedOperationsOperationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/experiences/$experienceId': typeof AuthenticatedExperiencesExperienceIdRoute
  '/_authenticated/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/_authenticated/operations/$operationId': typeof AuthenticatedOperationsOperationIdRouteWithChildren
  '/_authenticated/experiences/': typeof AuthenticatedExperiencesIndexRoute
  '/_authenticated/operations/': typeof AuthenticatedOperationsIndexRoute
  '/_authenticated/operations/$operationId/': typeof AuthenticatedOperationsOperationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/onboarding'
    | '/people'
    | '/settings'
    | '/team'
    | '/experiences/$experienceId'
    | '/invite/$token'
    | '/operations/$operationId'
    | '/experiences/'
    | '/operations/'
    | '/operations/$operationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/onboarding'
    | '/people'
    | '/settings'
    | '/team'
    | '/experiences/$experienceId'
    | '/invite/$token'
    | '/experiences'
    | '/operations'
    | '/operations/$operationId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/people'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/experiences/$experienceId'
    | '/_authenticated/invite/$token'
    | '/_authenticated/operations/$operationId'
    | '/_authenticated/experiences/'
    | '/_authenticated/operations/'
    | '/_authenticated/operations/$operationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiences/': {
      id: '/_authenticated/experiences/'
      path: '/experiences'
      fullPath: '/experiences/'
      preLoaderRoute: typeof AuthenticatedExperiencesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiences/$experienceId': {
      id: '/_authenticated/experiences/$experienceId'
      path: '/experiences/$experienceId'
      fullPath: '/experiences/$experienceId'
      preLoaderRoute: typeof AuthenticatedExperiencesExperienceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invite/$token': {
      id: '/_authenticated/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AuthenticatedInviteTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations/': {
      id: '/_authenticated/operations/'
      path: '/operations'
      fullPath: '/operations/'
      preLoaderRoute: typeof AuthenticatedOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations/$operationId': {
      id: '/_authenticated/operations/$operationId'
      path: '/operations/$operationId'
      fullPath: '/operations/$operationId'
      preLoaderRoute: typeof AuthenticatedOperationsOperationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations/$operationId/': {
      id: '/_authenticated/operations/$operationId/'
      path: '/'
      fullPath: '/operations/$operationId/'
      preLoaderRoute: typeof AuthenticatedOperationsOperationIdIndexRouteImport
      parentRoute: typeof AuthenticatedOperationsOperationIdRoute
    }
  }
}

interface AuthenticatedOperationsOperationIdRouteChildren {
  AuthenticatedOperationsOperationIdIndexRoute: typeof AuthenticatedOperationsOperationIdIndexRoute
}

const AuthenticatedOperationsOperationIdRouteChildren: AuthenticatedOperationsOperationIdRouteChildren =
  {
    AuthenticatedOperationsOperationIdIndexRoute:
      AuthenticatedOperationsOperationIdIndexRoute,
  }

const AuthenticatedOperationsOperationIdRouteWithChildren =
  AuthenticatedOperationsOperationIdRoute._addFileChildren(
    AuthenticatedOperationsOperationIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedExperiencesExperienceIdRoute: typeof AuthenticatedExperiencesExperienceIdRoute
  AuthenticatedInviteTokenRoute: typeof AuthenticatedInviteTokenRoute
  AuthenticatedOperationsOperationIdRoute: typeof AuthenticatedOperationsOperationIdRouteWithChildren
  AuthenticatedExperiencesIndexRoute: typeof AuthenticatedExperiencesIndexRoute
  AuthenticatedOperationsIndexRoute: typeof AuthenticatedOperationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedExperiencesExperienceIdRoute:
    AuthenticatedExperiencesExperienceIdRoute,
  AuthenticatedInviteTokenRoute: AuthenticatedInviteTokenRoute,
  AuthenticatedOperationsOperationIdRoute:
    AuthenticatedOperationsOperationIdRouteWithChildren,
  AuthenticatedExperiencesIndexRoute: AuthenticatedExperiencesIndexRoute,
  AuthenticatedOperationsIndexRoute: AuthenticatedOperationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
