-- COBS OS · Contract document source gate v1
-- Establishes the immutable source required by generated-document upload mode.
-- No legal text is inserted, no template is activated and no PDF/provider action occurs.

alter table public.contract_templates
  add column if not exists document_source_snapshot text,
  add column if not exists document_source_hash text,
  add column if not exists document_renderer_version text;

comment on column public.contract_templates.document_source_snapshot is
  'Exact frozen source used to render a generated contract document. It must contain only the real reviewed contract text; it is never auto-generated by COBS.';
comment on column public.contract_templates.document_source_hash is
  'Server-verifiable SHA-256 of document_source_snapshot.';
comment on column public.contract_templates.document_renderer_version is
  'Explicit version identifier of the renderer that converts the frozen document source into the provider-upload document.';

create or replace function app_private.guard_contract_template_upload_document_source()
returns trigger
language plpgsql
security definer
set search_path='public','app_private','pg_temp'
as $$
declare
  v_source text;
  v_expected_hash text;
  v_mode text;
begin
  v_mode := nullif(btrim(coalesce(new.metadata->>'provider_document_mode','')),'');

  if new.template_key='CIOSP-2027'
     and new.status='active'
     and v_mode='upload' then
    v_source := nullif(btrim(coalesce(new.document_source_snapshot,'')),'');

    if v_source is null or char_length(v_source) < 200 then
      raise exception 'contract_document_source_required';
    end if;

    v_expected_hash := encode(
      digest(convert_to(v_source,'UTF8'),'sha256'),
      'hex'
    );

    if nullif(btrim(coalesce(new.document_source_hash,'')),'') is null
       or lower(new.document_source_hash) <> v_expected_hash then
      raise exception 'contract_document_source_hash_mismatch';
    end if;

    if nullif(btrim(coalesce(new.document_renderer_version,'')),'') is null then
      raise exception 'contract_document_renderer_required';
    end if;
  end if;

  return new;
end;
$$;

revoke all on function app_private.guard_contract_template_upload_document_source() from public;

drop trigger if exists contract_templates_upload_document_source_guard on public.contract_templates;
create trigger contract_templates_upload_document_source_guard
before insert or update of status,metadata,document_source_snapshot,document_source_hash,document_renderer_version
on public.contract_templates
for each row execute function app_private.guard_contract_template_upload_document_source();

create or replace function public.register_contract_document_source_draft(
  _template_id uuid,
  _document_source_snapshot text,
  _renderer_version text
) returns jsonb
language plpgsql
security definer
set search_path='public','app_private','pg_temp'
as $$
declare
  v_uid uuid := auth.uid();
  v_template public.contract_templates%rowtype;
  v_source text := nullif(btrim(coalesce(_document_source_snapshot,'')),'');
  v_renderer text := nullif(btrim(coalesce(_renderer_version,'')),'');
  v_hash text;
begin
  if v_uid is null then raise exception 'authentication_required'; end if;

  select * into v_template
  from public.contract_templates
  where id=_template_id
  for update;
  if not found then raise exception 'contract_template_not_found'; end if;

  if not app_private.has_tenant_role(
    v_template.tenant_id,
    array['owner','admin']::public.app_role[]
  ) then raise exception 'forbidden'; end if;

  if v_template.status not in ('draft','review_required')
     or v_template.legal_reviewed_at is not null then
    raise exception 'contract_document_source_registration_closed';
  end if;

  if v_source is null or char_length(v_source) < 200 then
    raise exception 'contract_document_source_required';
  end if;
  if v_renderer is null then raise exception 'contract_document_renderer_required'; end if;

  v_hash := encode(digest(convert_to(v_source,'UTF8'),'sha256'),'hex');

  update public.contract_templates
  set document_source_snapshot=v_source,
      document_source_hash=v_hash,
      document_renderer_version=v_renderer,
      updated_at=now()
  where id=v_template.id;

  perform app_private.record_audit_event(
    v_template.tenant_id,
    v_uid,
    'contract_template.document_source_registered',
    'contract_template',
    v_template.id,
    null,
    jsonb_build_object(
      'template_key',v_template.template_key,
      'template_version',v_template.version,
      'document_source_hash',v_hash,
      'renderer_version',v_renderer,
      'status',v_template.status,
      'formal_legal_review_recorded',false
    )
  );

  return jsonb_build_object(
    'template_id',v_template.id,
    'template_key',v_template.template_key,
    'template_version',v_template.version,
    'status',v_template.status,
    'document_source_hash',v_hash,
    'renderer_version',v_renderer,
    'legal_reviewed_at',null
  );
end;
$$;

revoke all on function public.register_contract_document_source_draft(uuid,text,text) from public,anon;
grant execute on function public.register_contract_document_source_draft(uuid,text,text) to authenticated,service_role;

comment on function public.register_contract_document_source_draft(uuid,text,text) is
  'Registers an exact draft/review-required contract document source and computes SHA-256 server-side. It never records legal approval or activates the template.';

-- Replace the read-only diagnostic so upload readiness requires all three technical artifacts:
-- frozen source, valid hash and renderer version.
create or replace function public.get_contract_document_pipeline_readiness(
  _operation_id uuid,
  _template_key text default 'CIOSP-2027'
) returns jsonb
language plpgsql
security definer
set search_path='public','app_private','pg_temp'
as $$
declare
  v_uid uuid := auth.uid();
  v_operation public.operations%rowtype;
  v_template record;
  v_template_key text := nullif(btrim(coalesce(_template_key,'')),'');
  v_mode text;
  v_source text;
  v_hash text;
  v_expected_hash text;
  v_renderer_version text;
  v_provider_template_id text;
  v_source_valid boolean := false;
  v_ready boolean := false;
begin
  if v_uid is null then raise exception 'authentication_required'; end if;
  if v_template_key is null then raise exception 'template_key_required'; end if;

  select * into v_operation from public.operations where id=_operation_id;
  if not found then raise exception 'operation_not_found'; end if;
  if not app_private.has_tenant_role(
    v_operation.tenant_id,
    array['owner','admin','operations_agent']::public.app_role[]
  ) then raise exception 'forbidden'; end if;

  select ct.id,ct.version,ct.status,ct.provider,ct.provider_template_id,ct.metadata,
         ct.document_source_snapshot,ct.document_source_hash,ct.document_renderer_version
  into v_template
  from public.contract_templates ct
  where ct.tenant_id=v_operation.tenant_id and ct.template_key=v_template_key
  order by case when ct.version='V3.1' then 0 else 1 end,ct.created_at desc
  limit 1;

  if v_template.id is null then
    return jsonb_build_object('ready',false,'status','blocked','mode','missing','detail','contract_template_missing');
  end if;

  v_mode := nullif(btrim(coalesce(v_template.metadata->>'provider_document_mode','')),'');
  v_source := nullif(btrim(coalesce(v_template.document_source_snapshot,'')),'');
  v_hash := nullif(btrim(coalesce(v_template.document_source_hash,'')),'');
  v_renderer_version := nullif(btrim(coalesce(v_template.document_renderer_version,'')),'');
  v_provider_template_id := nullif(btrim(coalesce(v_template.provider_template_id,'')),'');

  if v_source is not null and char_length(v_source) >= 200 then
    v_expected_hash := encode(digest(convert_to(v_source,'UTF8'),'sha256'),'hex');
    v_source_valid := v_hash is not null and lower(v_hash)=v_expected_hash;
  end if;

  if v_mode='upload' then
    v_ready := v_source_valid and v_renderer_version is not null;
  elsif v_mode='provider_template' then
    v_ready := v_provider_template_id is not null;
  end if;

  return jsonb_build_object(
    'ready',v_ready,
    'status',case when v_ready then 'ready' else 'blocked' end,
    'mode',coalesce(v_mode,'missing'),
    'template_version',v_template.version,
    'document_source_frozen',v_source is not null,
    'document_source_hash_valid',v_source_valid,
    'renderer_version',v_renderer_version,
    'provider_template_configured',v_provider_template_id is not null,
    'detail',case
      when v_mode='upload' and v_source is null then 'document_source_not_registered'
      when v_mode='upload' and not v_source_valid then 'document_source_hash_invalid'
      when v_mode='upload' and v_renderer_version is null then 'upload_renderer_not_registered'
      when v_mode='provider_template' and v_provider_template_id is null then 'provider_template_not_configured'
      when v_mode is null then 'provider_document_mode_missing'
      when v_ready then 'document_pipeline_configured'
      else 'document_pipeline_not_configured'
    end,
    'note','Diagnóstico somente leitura. Não gera PDF nem chama provedor.'
  );
end;
$$;

revoke all on function public.get_contract_document_pipeline_readiness(uuid,text) from public,anon;
grant execute on function public.get_contract_document_pipeline_readiness(uuid,text) to authenticated,service_role;
