// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

/**
 * TEMPORARY production-payment smoke-test routing.
 *
 * This branch is intentionally pinned to COBS OS CLEAN BUILD so an authenticated
 * owner can execute a controlled R$ 1 Mercado Pago production smoke test.
 * Do not merge this branch into main or the regular V3.1 QA branch.
 */
const SMOKE_SUPABASE_URL = "https://nktohbqmcpgonlizzcka.supabase.co";
const SMOKE_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_yF0oXJtt-_ik8kq_FiGrdQ_2IwM4tzJ";

function createSupabaseClient() {
  const SUPABASE_URL = SMOKE_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = SMOKE_SUPABASE_PUBLISHABLE_KEY;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
