// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

const CIOSP_QA_HOST = "cobs-os-qa-git-feat-ciosp-c-ff63d9-contatobsbtur-7062s-projects.vercel.app";

function canonicalizeCiospPreviewHost() {
  if (typeof window === "undefined") return;

  const { hostname, pathname, search, hash } = window.location;
  const immutableVercelPreview =
    hostname.startsWith("cobs-os-") &&
    !hostname.includes("-git-") &&
    hostname.endsWith("-contatobsbtur-7062s-projects.vercel.app");

  if (immutableVercelPreview && hostname !== CIOSP_QA_HOST) {
    window.location.replace(`https://${CIOSP_QA_HOST}${pathname}${search}${hash}`);
  }
}

canonicalizeCiospPreviewHost();

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function isCiospCommercialPreview(): boolean {
  if (typeof window === "undefined") return false;

  const hostname = window.location.hostname;

  return (
    hostname === CIOSP_QA_HOST ||
    (hostname.startsWith("cobs-os-") && hostname.endsWith("-contatobsbtur-7062s-projects.vercel.app"))
  );
}

function createSupabaseClient() {
  const previewUsesStaging = isCiospCommercialPreview();

  const SUPABASE_URL = previewUsesStaging
    ? "https://wzukfenbzwlwzhtadlxl.supabase.co"
    : import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"];

  const SUPABASE_PUBLISHABLE_KEY = previewUsesStaging
    ? "sb_publishable_jDx7luxp7vohloi1dm8MXQ_g_Zxmsv0"
    : import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});