// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

/**
 * V3.1 QA-only backend routing.
 *
 * This file is being used from the isolated branch
 * `feat/v3.1-b6-3-ui-product-integration`. Every browser/server execution of this
 * branch must use the authorized secondary Supabase project used as the QA sandbox.
 *
 * The frozen V1 production/main continues to use its normal environment variables.
 * The key below is a Supabase publishable key (client-safe by design), not a secret.
 * This branch-only override MUST be removed before any V3.1 PR is merged to main.
 */
const V31_QA_SUPABASE_URL = "https://mkjuoijrtbporbjkztla.supabase.co";
const V31_QA_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_oGAygTekqi0WQvy4KbMsCA_8my6jvkD";

function isV31Preview(): boolean {
  // B6.3 QA Environment Alignment:
  // the isolated branch is intentionally pinned to the V3.1 sandbox on both SSR
  // and the hydrated browser. The previous hostname heuristic failed on Vercel's
  // generated deployment host (cobs-os-<hash>-...), causing the browser to fall
  // back to CLEAN BUILD after hydration.
  if (typeof window !== "undefined") return true;
  return (process.env["VERCEL_GIT_COMMIT_REF"] ?? "").startsWith("feat/v3.1-");
}

function createSupabaseClient() {
  const preview = isV31Preview();

  const SUPABASE_URL = preview
    ? V31_QA_SUPABASE_URL
    : import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY = preview
    ? V31_QA_SUPABASE_PUBLISHABLE_KEY
    : import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
